syntax = "proto3";

package oceanstars.iam.protobuf;

import "google/protobuf/any.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";
import "oceanstars/protobuf/cqrs.proto";
import "google/protobuf/descriptor.proto";

option java_multiple_files = true;
option java_package = "oceanstars.ecommerce.iam.api.rpc.v1.dto.authn";

// 注册命令实体
message IamSignupCommand {
  // 账号域
  int32 domain = 1;
  // 账号访问方式
  string access = 2;
  // 账号访问类型
  int32 accessType = 3;
  // 密码
  string password = 4;
  // 用户名
  string userName = 5;
  // 是否同意协议和隐私政策
  bool agree = 6;
}

// 注册返回结果实体
message IamSignupResult {
  // 真实性验证令牌
  string token = 1;
}