/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.message.repository.generate;


import java.util.Arrays;
import java.util.List;

import oceanstars.ecommerce.message.repository.generate.tables.MessageEventMeta;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>message_event_meta</code>.
     */
    public final MessageEventMeta MESSAGE_EVENT_META = MessageEventMeta.MESSAGE_EVENT_META;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            MessageEventMeta.MESSAGE_EVENT_META
        );
    }
}
