/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.message.repository.generate;


import oceanstars.ecommerce.message.repository.generate.tables.MessageEventMeta;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_BUS = Internal.createIndex(DSL.name("idx_bus"), MessageEventMeta.MESSAGE_EVENT_META, new OrderField[] { MessageEventMeta.MESSAGE_EVENT_META.BUS }, false);
    public static final Index IDX_TYPE = Internal.createIndex(DSL.name("idx_type"), MessageEventMeta.MESSAGE_EVENT_META, new OrderField[] { MessageEventMeta.MESSAGE_EVENT_META.TYPE }, false);
}
