/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.message.repository.generate;


import oceanstars.ecommerce.message.repository.generate.tables.MessageEventMeta;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>message_event_meta</code>.
     */
    public static final MessageEventMeta MESSAGE_EVENT_META = MessageEventMeta.MESSAGE_EVENT_META;
}
