/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.user.repository.generate.tables.records;


import java.time.LocalDateTime;

import oceanstars.ecommerce.user.repository.generate.tables.RelAccountRole;
import oceanstars.ecommerce.user.repository.generate.tables.interfaces.IRelAccountRole;
import oceanstars.ecommerce.user.repository.generate.tables.pojos.RelAccountRolePojo;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RelAccountRoleRecord extends UpdatableRecordImpl<RelAccountRoleRecord> implements Record5<Long, Long, Long, String, LocalDateTime>, IRelAccountRole {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rel_account_role.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>rel_account_role.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>rel_account_role.aid</code>.
     */
    @Override
    public void setAid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>rel_account_role.aid</code>.
     */
    @Override
    public Long getAid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>rel_account_role.rid</code>.
     */
    @Override
    public void setRid(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>rel_account_role.rid</code>.
     */
    @Override
    public Long getRid() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>rel_account_role.create_by</code>.
     */
    @Override
    public void setCreateBy(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rel_account_role.create_by</code>.
     */
    @Override
    public String getCreateBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>rel_account_role.create_at</code>.
     */
    @Override
    public void setCreateAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>rel_account_role.create_at</code>.
     */
    @Override
    public LocalDateTime getCreateAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, Long, String, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Long, Long, String, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return RelAccountRole.REL_ACCOUNT_ROLE.ID;
    }

    @Override
    public Field<Long> field2() {
        return RelAccountRole.REL_ACCOUNT_ROLE.AID;
    }

    @Override
    public Field<Long> field3() {
        return RelAccountRole.REL_ACCOUNT_ROLE.RID;
    }

    @Override
    public Field<String> field4() {
        return RelAccountRole.REL_ACCOUNT_ROLE.CREATE_BY;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return RelAccountRole.REL_ACCOUNT_ROLE.CREATE_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getAid();
    }

    @Override
    public Long component3() {
        return getRid();
    }

    @Override
    public String component4() {
        return getCreateBy();
    }

    @Override
    public LocalDateTime component5() {
        return getCreateAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getAid();
    }

    @Override
    public Long value3() {
        return getRid();
    }

    @Override
    public String value4() {
        return getCreateBy();
    }

    @Override
    public LocalDateTime value5() {
        return getCreateAt();
    }

    @Override
    public RelAccountRoleRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public RelAccountRoleRecord value2(Long value) {
        setAid(value);
        return this;
    }

    @Override
    public RelAccountRoleRecord value3(Long value) {
        setRid(value);
        return this;
    }

    @Override
    public RelAccountRoleRecord value4(String value) {
        setCreateBy(value);
        return this;
    }

    @Override
    public RelAccountRoleRecord value5(LocalDateTime value) {
        setCreateAt(value);
        return this;
    }

    @Override
    public RelAccountRoleRecord values(Long value1, Long value2, Long value3, String value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IRelAccountRole from) {
        setId(from.getId());
        setAid(from.getAid());
        setRid(from.getRid());
        setCreateBy(from.getCreateBy());
        setCreateAt(from.getCreateAt());
    }

    @Override
    public <E extends IRelAccountRole> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RelAccountRoleRecord
     */
    public RelAccountRoleRecord() {
        super(RelAccountRole.REL_ACCOUNT_ROLE);
    }

    /**
     * Create a detached, initialised RelAccountRoleRecord
     */
    public RelAccountRoleRecord(Long id, Long aid, Long rid, String createBy, LocalDateTime createAt) {
        super(RelAccountRole.REL_ACCOUNT_ROLE);

        setId(id);
        setAid(aid);
        setRid(rid);
        setCreateBy(createBy);
        setCreateAt(createAt);
    }

    /**
     * Create a detached, initialised RelAccountRoleRecord
     */
    public RelAccountRoleRecord(RelAccountRolePojo value) {
        super(RelAccountRole.REL_ACCOUNT_ROLE);

        if (value != null) {
            setId(value.getId());
            setAid(value.getAid());
            setRid(value.getRid());
            setCreateBy(value.getCreateBy());
            setCreateAt(value.getCreateAt());
        }
    }
}
