/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.user.repository.generate.tables.records;


import java.time.LocalDateTime;

import oceanstars.ecommerce.user.repository.generate.tables.RelPermissionResource;
import oceanstars.ecommerce.user.repository.generate.tables.interfaces.IRelPermissionResource;
import oceanstars.ecommerce.user.repository.generate.tables.pojos.RelPermissionResourcePojo;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RelPermissionResourceRecord extends UpdatableRecordImpl<RelPermissionResourceRecord> implements Record7<Long, Long, Long, Long, Long, String, LocalDateTime>, IRelPermissionResource {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rel_permission_resource.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>rel_permission_resource.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>rel_permission_resource.pid</code>.
     */
    @Override
    public void setPid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>rel_permission_resource.pid</code>.
     */
    @Override
    public Long getPid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>rel_permission_resource.rid</code>.
     */
    @Override
    public void setRid(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>rel_permission_resource.rid</code>.
     */
    @Override
    public Long getRid() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>rel_permission_resource.tid</code>.
     */
    @Override
    public void setTid(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>rel_permission_resource.tid</code>.
     */
    @Override
    public Long getTid() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>rel_permission_resource.oid</code>.
     */
    @Override
    public void setOid(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>rel_permission_resource.oid</code>.
     */
    @Override
    public Long getOid() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>rel_permission_resource.create_by</code>.
     */
    @Override
    public void setCreateBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>rel_permission_resource.create_by</code>.
     */
    @Override
    public String getCreateBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>rel_permission_resource.create_at</code>.
     */
    @Override
    public void setCreateAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>rel_permission_resource.create_at</code>.
     */
    @Override
    public LocalDateTime getCreateAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, Long, Long, Long, String, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Long, Long, Long, Long, String, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return RelPermissionResource.REL_PERMISSION_RESOURCE.ID;
    }

    @Override
    public Field<Long> field2() {
        return RelPermissionResource.REL_PERMISSION_RESOURCE.PID;
    }

    @Override
    public Field<Long> field3() {
        return RelPermissionResource.REL_PERMISSION_RESOURCE.RID;
    }

    @Override
    public Field<Long> field4() {
        return RelPermissionResource.REL_PERMISSION_RESOURCE.TID;
    }

    @Override
    public Field<Long> field5() {
        return RelPermissionResource.REL_PERMISSION_RESOURCE.OID;
    }

    @Override
    public Field<String> field6() {
        return RelPermissionResource.REL_PERMISSION_RESOURCE.CREATE_BY;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return RelPermissionResource.REL_PERMISSION_RESOURCE.CREATE_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getPid();
    }

    @Override
    public Long component3() {
        return getRid();
    }

    @Override
    public Long component4() {
        return getTid();
    }

    @Override
    public Long component5() {
        return getOid();
    }

    @Override
    public String component6() {
        return getCreateBy();
    }

    @Override
    public LocalDateTime component7() {
        return getCreateAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getPid();
    }

    @Override
    public Long value3() {
        return getRid();
    }

    @Override
    public Long value4() {
        return getTid();
    }

    @Override
    public Long value5() {
        return getOid();
    }

    @Override
    public String value6() {
        return getCreateBy();
    }

    @Override
    public LocalDateTime value7() {
        return getCreateAt();
    }

    @Override
    public RelPermissionResourceRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public RelPermissionResourceRecord value2(Long value) {
        setPid(value);
        return this;
    }

    @Override
    public RelPermissionResourceRecord value3(Long value) {
        setRid(value);
        return this;
    }

    @Override
    public RelPermissionResourceRecord value4(Long value) {
        setTid(value);
        return this;
    }

    @Override
    public RelPermissionResourceRecord value5(Long value) {
        setOid(value);
        return this;
    }

    @Override
    public RelPermissionResourceRecord value6(String value) {
        setCreateBy(value);
        return this;
    }

    @Override
    public RelPermissionResourceRecord value7(LocalDateTime value) {
        setCreateAt(value);
        return this;
    }

    @Override
    public RelPermissionResourceRecord values(Long value1, Long value2, Long value3, Long value4, Long value5, String value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IRelPermissionResource from) {
        setId(from.getId());
        setPid(from.getPid());
        setRid(from.getRid());
        setTid(from.getTid());
        setOid(from.getOid());
        setCreateBy(from.getCreateBy());
        setCreateAt(from.getCreateAt());
    }

    @Override
    public <E extends IRelPermissionResource> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RelPermissionResourceRecord
     */
    public RelPermissionResourceRecord() {
        super(RelPermissionResource.REL_PERMISSION_RESOURCE);
    }

    /**
     * Create a detached, initialised RelPermissionResourceRecord
     */
    public RelPermissionResourceRecord(Long id, Long pid, Long rid, Long tid, Long oid, String createBy, LocalDateTime createAt) {
        super(RelPermissionResource.REL_PERMISSION_RESOURCE);

        setId(id);
        setPid(pid);
        setRid(rid);
        setTid(tid);
        setOid(oid);
        setCreateBy(createBy);
        setCreateAt(createAt);
    }

    /**
     * Create a detached, initialised RelPermissionResourceRecord
     */
    public RelPermissionResourceRecord(RelPermissionResourcePojo value) {
        super(RelPermissionResource.REL_PERMISSION_RESOURCE);

        if (value != null) {
            setId(value.getId());
            setPid(value.getPid());
            setRid(value.getRid());
            setTid(value.getTid());
            setOid(value.getOid());
            setCreateBy(value.getCreateBy());
            setCreateAt(value.getCreateAt());
        }
    }
}
