/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.user.repository.generate.tables.records;


import java.time.LocalDateTime;

import oceanstars.ecommerce.user.repository.generate.tables.UserRole;
import oceanstars.ecommerce.user.repository.generate.tables.interfaces.IUserRole;
import oceanstars.ecommerce.user.repository.generate.tables.pojos.UserRolePojo;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRoleRecord extends UpdatableRecordImpl<UserRoleRecord> implements Record10<Long, String, String, String, Boolean, String, LocalDateTime, String, LocalDateTime, Integer>, IUserRole {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>user_role.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>user_role.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>user_role.code</code>.
     */
    @Override
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>user_role.code</code>.
     */
    @Override
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>user_role.name</code>.
     */
    @Override
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>user_role.name</code>.
     */
    @Override
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>user_role.desc</code>.
     */
    @Override
    public void setDesc(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>user_role.desc</code>.
     */
    @Override
    public String getDesc() {
        return (String) get(3);
    }

    /**
     * Setter for <code>user_role.enabled</code>.
     */
    @Override
    public void setEnabled(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>user_role.enabled</code>.
     */
    @Override
    public Boolean getEnabled() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>user_role.create_by</code>.
     */
    @Override
    public void setCreateBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>user_role.create_by</code>.
     */
    @Override
    public String getCreateBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>user_role.create_at</code>.
     */
    @Override
    public void setCreateAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>user_role.create_at</code>.
     */
    @Override
    public LocalDateTime getCreateAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>user_role.update_by</code>.
     */
    @Override
    public void setUpdateBy(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>user_role.update_by</code>.
     */
    @Override
    public String getUpdateBy() {
        return (String) get(7);
    }

    /**
     * Setter for <code>user_role.update_at</code>.
     */
    @Override
    public void setUpdateAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>user_role.update_at</code>.
     */
    @Override
    public LocalDateTime getUpdateAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>user_role.version</code>.
     */
    @Override
    public void setVersion(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>user_role.version</code>.
     */
    @Override
    public Integer getVersion() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, String, String, Boolean, String, LocalDateTime, String, LocalDateTime, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, String, String, String, Boolean, String, LocalDateTime, String, LocalDateTime, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserRole.USER_ROLE.ID;
    }

    @Override
    public Field<String> field2() {
        return UserRole.USER_ROLE.CODE;
    }

    @Override
    public Field<String> field3() {
        return UserRole.USER_ROLE.NAME;
    }

    @Override
    public Field<String> field4() {
        return UserRole.USER_ROLE.DESC;
    }

    @Override
    public Field<Boolean> field5() {
        return UserRole.USER_ROLE.ENABLED;
    }

    @Override
    public Field<String> field6() {
        return UserRole.USER_ROLE.CREATE_BY;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return UserRole.USER_ROLE.CREATE_AT;
    }

    @Override
    public Field<String> field8() {
        return UserRole.USER_ROLE.UPDATE_BY;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return UserRole.USER_ROLE.UPDATE_AT;
    }

    @Override
    public Field<Integer> field10() {
        return UserRole.USER_ROLE.VERSION;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCode();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getDesc();
    }

    @Override
    public Boolean component5() {
        return getEnabled();
    }

    @Override
    public String component6() {
        return getCreateBy();
    }

    @Override
    public LocalDateTime component7() {
        return getCreateAt();
    }

    @Override
    public String component8() {
        return getUpdateBy();
    }

    @Override
    public LocalDateTime component9() {
        return getUpdateAt();
    }

    @Override
    public Integer component10() {
        return getVersion();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCode();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getDesc();
    }

    @Override
    public Boolean value5() {
        return getEnabled();
    }

    @Override
    public String value6() {
        return getCreateBy();
    }

    @Override
    public LocalDateTime value7() {
        return getCreateAt();
    }

    @Override
    public String value8() {
        return getUpdateBy();
    }

    @Override
    public LocalDateTime value9() {
        return getUpdateAt();
    }

    @Override
    public Integer value10() {
        return getVersion();
    }

    @Override
    public UserRoleRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserRoleRecord value2(String value) {
        setCode(value);
        return this;
    }

    @Override
    public UserRoleRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public UserRoleRecord value4(String value) {
        setDesc(value);
        return this;
    }

    @Override
    public UserRoleRecord value5(Boolean value) {
        setEnabled(value);
        return this;
    }

    @Override
    public UserRoleRecord value6(String value) {
        setCreateBy(value);
        return this;
    }

    @Override
    public UserRoleRecord value7(LocalDateTime value) {
        setCreateAt(value);
        return this;
    }

    @Override
    public UserRoleRecord value8(String value) {
        setUpdateBy(value);
        return this;
    }

    @Override
    public UserRoleRecord value9(LocalDateTime value) {
        setUpdateAt(value);
        return this;
    }

    @Override
    public UserRoleRecord value10(Integer value) {
        setVersion(value);
        return this;
    }

    @Override
    public UserRoleRecord values(Long value1, String value2, String value3, String value4, Boolean value5, String value6, LocalDateTime value7, String value8, LocalDateTime value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUserRole from) {
        setId(from.getId());
        setCode(from.getCode());
        setName(from.getName());
        setDesc(from.getDesc());
        setEnabled(from.getEnabled());
        setCreateBy(from.getCreateBy());
        setCreateAt(from.getCreateAt());
        setUpdateBy(from.getUpdateBy());
        setUpdateAt(from.getUpdateAt());
        setVersion(from.getVersion());
    }

    @Override
    public <E extends IUserRole> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRoleRecord
     */
    public UserRoleRecord() {
        super(UserRole.USER_ROLE);
    }

    /**
     * Create a detached, initialised UserRoleRecord
     */
    public UserRoleRecord(Long id, String code, String name, String desc, Boolean enabled, String createBy, LocalDateTime createAt, String updateBy, LocalDateTime updateAt, Integer version) {
        super(UserRole.USER_ROLE);

        setId(id);
        setCode(code);
        setName(name);
        setDesc(desc);
        setEnabled(enabled);
        setCreateBy(createBy);
        setCreateAt(createAt);
        setUpdateBy(updateBy);
        setUpdateAt(updateAt);
        setVersion(version);
    }

    /**
     * Create a detached, initialised UserRoleRecord
     */
    public UserRoleRecord(UserRolePojo value) {
        super(UserRole.USER_ROLE);

        if (value != null) {
            setId(value.getId());
            setCode(value.getCode());
            setName(value.getName());
            setDesc(value.getDesc());
            setEnabled(value.getEnabled());
            setCreateBy(value.getCreateBy());
            setCreateAt(value.getCreateAt());
            setUpdateBy(value.getUpdateBy());
            setUpdateAt(value.getUpdateAt());
            setVersion(value.getVersion());
        }
    }
}
