/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.user.repository.generate.tables.records;


import java.time.LocalDateTime;

import oceanstars.ecommerce.user.repository.generate.tables.UserPermission;
import oceanstars.ecommerce.user.repository.generate.tables.interfaces.IUserPermission;
import oceanstars.ecommerce.user.repository.generate.tables.pojos.UserPermissionPojo;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserPermissionRecord extends UpdatableRecordImpl<UserPermissionRecord> implements Record11<Long, String, String, Short, String, Boolean, String, LocalDateTime, String, LocalDateTime, Integer>, IUserPermission {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>user_permission.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>user_permission.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>user_permission.code</code>.
     */
    @Override
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>user_permission.code</code>.
     */
    @Override
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>user_permission.name</code>.
     */
    @Override
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>user_permission.name</code>.
     */
    @Override
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>user_permission.type</code>.
     */
    @Override
    public void setType(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>user_permission.type</code>.
     */
    @Override
    public Short getType() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>user_permission.desc</code>.
     */
    @Override
    public void setDesc(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>user_permission.desc</code>.
     */
    @Override
    public String getDesc() {
        return (String) get(4);
    }

    /**
     * Setter for <code>user_permission.enabled</code>.
     */
    @Override
    public void setEnabled(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>user_permission.enabled</code>.
     */
    @Override
    public Boolean getEnabled() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>user_permission.create_by</code>.
     */
    @Override
    public void setCreateBy(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>user_permission.create_by</code>.
     */
    @Override
    public String getCreateBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>user_permission.create_at</code>.
     */
    @Override
    public void setCreateAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>user_permission.create_at</code>.
     */
    @Override
    public LocalDateTime getCreateAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>user_permission.update_by</code>.
     */
    @Override
    public void setUpdateBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>user_permission.update_by</code>.
     */
    @Override
    public String getUpdateBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>user_permission.update_at</code>.
     */
    @Override
    public void setUpdateAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>user_permission.update_at</code>.
     */
    @Override
    public LocalDateTime getUpdateAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>user_permission.version</code>.
     */
    @Override
    public void setVersion(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>user_permission.version</code>.
     */
    @Override
    public Integer getVersion() {
        return (Integer) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, String, String, Short, String, Boolean, String, LocalDateTime, String, LocalDateTime, Integer> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, String, String, Short, String, Boolean, String, LocalDateTime, String, LocalDateTime, Integer> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserPermission.USER_PERMISSION.ID;
    }

    @Override
    public Field<String> field2() {
        return UserPermission.USER_PERMISSION.CODE;
    }

    @Override
    public Field<String> field3() {
        return UserPermission.USER_PERMISSION.NAME;
    }

    @Override
    public Field<Short> field4() {
        return UserPermission.USER_PERMISSION.TYPE;
    }

    @Override
    public Field<String> field5() {
        return UserPermission.USER_PERMISSION.DESC;
    }

    @Override
    public Field<Boolean> field6() {
        return UserPermission.USER_PERMISSION.ENABLED;
    }

    @Override
    public Field<String> field7() {
        return UserPermission.USER_PERMISSION.CREATE_BY;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return UserPermission.USER_PERMISSION.CREATE_AT;
    }

    @Override
    public Field<String> field9() {
        return UserPermission.USER_PERMISSION.UPDATE_BY;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return UserPermission.USER_PERMISSION.UPDATE_AT;
    }

    @Override
    public Field<Integer> field11() {
        return UserPermission.USER_PERMISSION.VERSION;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCode();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Short component4() {
        return getType();
    }

    @Override
    public String component5() {
        return getDesc();
    }

    @Override
    public Boolean component6() {
        return getEnabled();
    }

    @Override
    public String component7() {
        return getCreateBy();
    }

    @Override
    public LocalDateTime component8() {
        return getCreateAt();
    }

    @Override
    public String component9() {
        return getUpdateBy();
    }

    @Override
    public LocalDateTime component10() {
        return getUpdateAt();
    }

    @Override
    public Integer component11() {
        return getVersion();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCode();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public Short value4() {
        return getType();
    }

    @Override
    public String value5() {
        return getDesc();
    }

    @Override
    public Boolean value6() {
        return getEnabled();
    }

    @Override
    public String value7() {
        return getCreateBy();
    }

    @Override
    public LocalDateTime value8() {
        return getCreateAt();
    }

    @Override
    public String value9() {
        return getUpdateBy();
    }

    @Override
    public LocalDateTime value10() {
        return getUpdateAt();
    }

    @Override
    public Integer value11() {
        return getVersion();
    }

    @Override
    public UserPermissionRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserPermissionRecord value2(String value) {
        setCode(value);
        return this;
    }

    @Override
    public UserPermissionRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public UserPermissionRecord value4(Short value) {
        setType(value);
        return this;
    }

    @Override
    public UserPermissionRecord value5(String value) {
        setDesc(value);
        return this;
    }

    @Override
    public UserPermissionRecord value6(Boolean value) {
        setEnabled(value);
        return this;
    }

    @Override
    public UserPermissionRecord value7(String value) {
        setCreateBy(value);
        return this;
    }

    @Override
    public UserPermissionRecord value8(LocalDateTime value) {
        setCreateAt(value);
        return this;
    }

    @Override
    public UserPermissionRecord value9(String value) {
        setUpdateBy(value);
        return this;
    }

    @Override
    public UserPermissionRecord value10(LocalDateTime value) {
        setUpdateAt(value);
        return this;
    }

    @Override
    public UserPermissionRecord value11(Integer value) {
        setVersion(value);
        return this;
    }

    @Override
    public UserPermissionRecord values(Long value1, String value2, String value3, Short value4, String value5, Boolean value6, String value7, LocalDateTime value8, String value9, LocalDateTime value10, Integer value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUserPermission from) {
        setId(from.getId());
        setCode(from.getCode());
        setName(from.getName());
        setType(from.getType());
        setDesc(from.getDesc());
        setEnabled(from.getEnabled());
        setCreateBy(from.getCreateBy());
        setCreateAt(from.getCreateAt());
        setUpdateBy(from.getUpdateBy());
        setUpdateAt(from.getUpdateAt());
        setVersion(from.getVersion());
    }

    @Override
    public <E extends IUserPermission> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserPermissionRecord
     */
    public UserPermissionRecord() {
        super(UserPermission.USER_PERMISSION);
    }

    /**
     * Create a detached, initialised UserPermissionRecord
     */
    public UserPermissionRecord(Long id, String code, String name, Short type, String desc, Boolean enabled, String createBy, LocalDateTime createAt, String updateBy, LocalDateTime updateAt, Integer version) {
        super(UserPermission.USER_PERMISSION);

        setId(id);
        setCode(code);
        setName(name);
        setType(type);
        setDesc(desc);
        setEnabled(enabled);
        setCreateBy(createBy);
        setCreateAt(createAt);
        setUpdateBy(updateBy);
        setUpdateAt(updateAt);
        setVersion(version);
    }

    /**
     * Create a detached, initialised UserPermissionRecord
     */
    public UserPermissionRecord(UserPermissionPojo value) {
        super(UserPermission.USER_PERMISSION);

        if (value != null) {
            setId(value.getId());
            setCode(value.getCode());
            setName(value.getName());
            setType(value.getType());
            setDesc(value.getDesc());
            setEnabled(value.getEnabled());
            setCreateBy(value.getCreateBy());
            setCreateAt(value.getCreateAt());
            setUpdateBy(value.getUpdateBy());
            setUpdateAt(value.getUpdateAt());
            setVersion(value.getVersion());
        }
    }
}
