/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.user.repository.generate.tables.records;


import java.time.LocalDateTime;

import oceanstars.ecommerce.user.repository.generate.tables.UserResourceType;
import oceanstars.ecommerce.user.repository.generate.tables.interfaces.IUserResourceType;
import oceanstars.ecommerce.user.repository.generate.tables.pojos.UserResourceTypePojo;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserResourceTypeRecord extends UpdatableRecordImpl<UserResourceTypeRecord> implements Record13<Long, String, String, String, String, String, String, Boolean, String, LocalDateTime, String, LocalDateTime, Integer>, IUserResourceType {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>user_resource_type.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>user_resource_type.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>user_resource_type.code</code>.
     */
    @Override
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>user_resource_type.code</code>.
     */
    @Override
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>user_resource_type.name</code>.
     */
    @Override
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>user_resource_type.name</code>.
     */
    @Override
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>user_resource_type.desc</code>.
     */
    @Override
    public void setDesc(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>user_resource_type.desc</code>.
     */
    @Override
    public String getDesc() {
        return (String) get(3);
    }

    /**
     * Setter for <code>user_resource_type.href</code>.
     */
    @Override
    public void setHref(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>user_resource_type.href</code>.
     */
    @Override
    public String getHref() {
        return (String) get(4);
    }

    /**
     * Setter for <code>user_resource_type.method</code>.
     */
    @Override
    public void setMethod(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>user_resource_type.method</code>.
     */
    @Override
    public String getMethod() {
        return (String) get(5);
    }

    /**
     * Setter for <code>user_resource_type.body</code>.
     */
    @Override
    public void setBody(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>user_resource_type.body</code>.
     */
    @Override
    public String getBody() {
        return (String) get(6);
    }

    /**
     * Setter for <code>user_resource_type.enabled</code>.
     */
    @Override
    public void setEnabled(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>user_resource_type.enabled</code>.
     */
    @Override
    public Boolean getEnabled() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>user_resource_type.create_by</code>.
     */
    @Override
    public void setCreateBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>user_resource_type.create_by</code>.
     */
    @Override
    public String getCreateBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>user_resource_type.create_at</code>.
     */
    @Override
    public void setCreateAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>user_resource_type.create_at</code>.
     */
    @Override
    public LocalDateTime getCreateAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>user_resource_type.update_by</code>.
     */
    @Override
    public void setUpdateBy(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>user_resource_type.update_by</code>.
     */
    @Override
    public String getUpdateBy() {
        return (String) get(10);
    }

    /**
     * Setter for <code>user_resource_type.update_at</code>.
     */
    @Override
    public void setUpdateAt(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>user_resource_type.update_at</code>.
     */
    @Override
    public LocalDateTime getUpdateAt() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>user_resource_type.version</code>.
     */
    @Override
    public void setVersion(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>user_resource_type.version</code>.
     */
    @Override
    public Integer getVersion() {
        return (Integer) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, String, String, String, String, String, String, Boolean, String, LocalDateTime, String, LocalDateTime, Integer> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Long, String, String, String, String, String, String, Boolean, String, LocalDateTime, String, LocalDateTime, Integer> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserResourceType.USER_RESOURCE_TYPE.ID;
    }

    @Override
    public Field<String> field2() {
        return UserResourceType.USER_RESOURCE_TYPE.CODE;
    }

    @Override
    public Field<String> field3() {
        return UserResourceType.USER_RESOURCE_TYPE.NAME;
    }

    @Override
    public Field<String> field4() {
        return UserResourceType.USER_RESOURCE_TYPE.DESC;
    }

    @Override
    public Field<String> field5() {
        return UserResourceType.USER_RESOURCE_TYPE.HREF;
    }

    @Override
    public Field<String> field6() {
        return UserResourceType.USER_RESOURCE_TYPE.METHOD;
    }

    @Override
    public Field<String> field7() {
        return UserResourceType.USER_RESOURCE_TYPE.BODY;
    }

    @Override
    public Field<Boolean> field8() {
        return UserResourceType.USER_RESOURCE_TYPE.ENABLED;
    }

    @Override
    public Field<String> field9() {
        return UserResourceType.USER_RESOURCE_TYPE.CREATE_BY;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return UserResourceType.USER_RESOURCE_TYPE.CREATE_AT;
    }

    @Override
    public Field<String> field11() {
        return UserResourceType.USER_RESOURCE_TYPE.UPDATE_BY;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return UserResourceType.USER_RESOURCE_TYPE.UPDATE_AT;
    }

    @Override
    public Field<Integer> field13() {
        return UserResourceType.USER_RESOURCE_TYPE.VERSION;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCode();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getDesc();
    }

    @Override
    public String component5() {
        return getHref();
    }

    @Override
    public String component6() {
        return getMethod();
    }

    @Override
    public String component7() {
        return getBody();
    }

    @Override
    public Boolean component8() {
        return getEnabled();
    }

    @Override
    public String component9() {
        return getCreateBy();
    }

    @Override
    public LocalDateTime component10() {
        return getCreateAt();
    }

    @Override
    public String component11() {
        return getUpdateBy();
    }

    @Override
    public LocalDateTime component12() {
        return getUpdateAt();
    }

    @Override
    public Integer component13() {
        return getVersion();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCode();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getDesc();
    }

    @Override
    public String value5() {
        return getHref();
    }

    @Override
    public String value6() {
        return getMethod();
    }

    @Override
    public String value7() {
        return getBody();
    }

    @Override
    public Boolean value8() {
        return getEnabled();
    }

    @Override
    public String value9() {
        return getCreateBy();
    }

    @Override
    public LocalDateTime value10() {
        return getCreateAt();
    }

    @Override
    public String value11() {
        return getUpdateBy();
    }

    @Override
    public LocalDateTime value12() {
        return getUpdateAt();
    }

    @Override
    public Integer value13() {
        return getVersion();
    }

    @Override
    public UserResourceTypeRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserResourceTypeRecord value2(String value) {
        setCode(value);
        return this;
    }

    @Override
    public UserResourceTypeRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public UserResourceTypeRecord value4(String value) {
        setDesc(value);
        return this;
    }

    @Override
    public UserResourceTypeRecord value5(String value) {
        setHref(value);
        return this;
    }

    @Override
    public UserResourceTypeRecord value6(String value) {
        setMethod(value);
        return this;
    }

    @Override
    public UserResourceTypeRecord value7(String value) {
        setBody(value);
        return this;
    }

    @Override
    public UserResourceTypeRecord value8(Boolean value) {
        setEnabled(value);
        return this;
    }

    @Override
    public UserResourceTypeRecord value9(String value) {
        setCreateBy(value);
        return this;
    }

    @Override
    public UserResourceTypeRecord value10(LocalDateTime value) {
        setCreateAt(value);
        return this;
    }

    @Override
    public UserResourceTypeRecord value11(String value) {
        setUpdateBy(value);
        return this;
    }

    @Override
    public UserResourceTypeRecord value12(LocalDateTime value) {
        setUpdateAt(value);
        return this;
    }

    @Override
    public UserResourceTypeRecord value13(Integer value) {
        setVersion(value);
        return this;
    }

    @Override
    public UserResourceTypeRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, Boolean value8, String value9, LocalDateTime value10, String value11, LocalDateTime value12, Integer value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUserResourceType from) {
        setId(from.getId());
        setCode(from.getCode());
        setName(from.getName());
        setDesc(from.getDesc());
        setHref(from.getHref());
        setMethod(from.getMethod());
        setBody(from.getBody());
        setEnabled(from.getEnabled());
        setCreateBy(from.getCreateBy());
        setCreateAt(from.getCreateAt());
        setUpdateBy(from.getUpdateBy());
        setUpdateAt(from.getUpdateAt());
        setVersion(from.getVersion());
    }

    @Override
    public <E extends IUserResourceType> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserResourceTypeRecord
     */
    public UserResourceTypeRecord() {
        super(UserResourceType.USER_RESOURCE_TYPE);
    }

    /**
     * Create a detached, initialised UserResourceTypeRecord
     */
    public UserResourceTypeRecord(Long id, String code, String name, String desc, String href, String method, String body, Boolean enabled, String createBy, LocalDateTime createAt, String updateBy, LocalDateTime updateAt, Integer version) {
        super(UserResourceType.USER_RESOURCE_TYPE);

        setId(id);
        setCode(code);
        setName(name);
        setDesc(desc);
        setHref(href);
        setMethod(method);
        setBody(body);
        setEnabled(enabled);
        setCreateBy(createBy);
        setCreateAt(createAt);
        setUpdateBy(updateBy);
        setUpdateAt(updateAt);
        setVersion(version);
    }

    /**
     * Create a detached, initialised UserResourceTypeRecord
     */
    public UserResourceTypeRecord(UserResourceTypePojo value) {
        super(UserResourceType.USER_RESOURCE_TYPE);

        if (value != null) {
            setId(value.getId());
            setCode(value.getCode());
            setName(value.getName());
            setDesc(value.getDesc());
            setHref(value.getHref());
            setMethod(value.getMethod());
            setBody(value.getBody());
            setEnabled(value.getEnabled());
            setCreateBy(value.getCreateBy());
            setCreateAt(value.getCreateAt());
            setUpdateBy(value.getUpdateBy());
            setUpdateAt(value.getUpdateAt());
            setVersion(value.getVersion());
        }
    }
}
