<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>oceanstars-ecommerce</groupId>
    <artifactId>iam</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <artifactId>iam-controller</artifactId>
  <version>${iam.controller.version}</version>

  <name>iam-controller</name>
  <description>iam facade layer project for oceanstars iam service</description>

  <properties>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-configuration-processor</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>oceanstars-ecommerce</groupId>
      <artifactId>iam-api-rest</artifactId>
      <version>${iam.api.rest.version}</version>
    </dependency>
    <dependency>
      <groupId>oceanstars-ecommerce</groupId>
      <artifactId>iam-application</artifactId>
      <version>${iam.application.version}</version>
    </dependency>
  </dependencies>

  <build>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <includes>
          <include>**/*.*</include>
        </includes>
        <excludes>
          <exclude>config/env-*/*.*</exclude>
        </excludes>
        <filtering>false</filtering>
      </resource>
      <resource>
        <targetPath>config</targetPath>
        <filtering>true</filtering>
        <directory>src/main/resources/config/env-${profileActive}</directory>
        <includes>
          <include>*.*</include>
        </includes>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
      <!--设置应用 Main 参数启动依赖查找的地址指向外部 lib 文件夹 -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <configuration>
          <archive>
            <manifest>
              <mainClass>oceanstars.ecommerce.oceanstars.ecommerce.iam.controller.IamControllerApplication</mainClass>
              <addClasspath>true</addClasspath>
              <classpathPrefix>lib/</classpathPrefix>
              <useUniqueVersions>false</useUniqueVersions>
            </manifest>
          </archive>
        </configuration>
      </plugin>
      <!--设置将 lib 拷贝到应用 Jar 外面 -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>copy-dependencies</id>
            <phase>prepare-package</phase>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <configuration>
              <outputDirectory>${project.build.directory}/lib</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>