/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.user.repository.generate.tables.pojos;


import java.time.LocalDateTime;

import oceanstars.ecommerce.user.repository.generate.tables.interfaces.IRelRoleRole;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RelRoleRolePojo implements IRelRoleRole {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long rid;
    private Long pid;
    private String createBy;
    private LocalDateTime createAt;

    public RelRoleRolePojo() {}

    public RelRoleRolePojo(IRelRoleRole value) {
        this.id = value.getId();
        this.rid = value.getRid();
        this.pid = value.getPid();
        this.createBy = value.getCreateBy();
        this.createAt = value.getCreateAt();
    }

    public RelRoleRolePojo(
        Long id,
        Long rid,
        Long pid,
        String createBy,
        LocalDateTime createAt
    ) {
        this.id = id;
        this.rid = rid;
        this.pid = pid;
        this.createBy = createBy;
        this.createAt = createAt;
    }

    /**
     * Getter for <code>rel_role_role.id</code>.
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>rel_role_role.id</code>.
     */
    @Override
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>rel_role_role.rid</code>.
     */
    @Override
    public Long getRid() {
        return this.rid;
    }

    /**
     * Setter for <code>rel_role_role.rid</code>.
     */
    @Override
    public void setRid(Long rid) {
        this.rid = rid;
    }

    /**
     * Getter for <code>rel_role_role.pid</code>.
     */
    @Override
    public Long getPid() {
        return this.pid;
    }

    /**
     * Setter for <code>rel_role_role.pid</code>.
     */
    @Override
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * Getter for <code>rel_role_role.create_by</code>.
     */
    @Override
    public String getCreateBy() {
        return this.createBy;
    }

    /**
     * Setter for <code>rel_role_role.create_by</code>.
     */
    @Override
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * Getter for <code>rel_role_role.create_at</code>.
     */
    @Override
    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    /**
     * Setter for <code>rel_role_role.create_at</code>.
     */
    @Override
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final RelRoleRolePojo other = (RelRoleRolePojo) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.rid == null) {
            if (other.rid != null)
                return false;
        }
        else if (!this.rid.equals(other.rid))
            return false;
        if (this.pid == null) {
            if (other.pid != null)
                return false;
        }
        else if (!this.pid.equals(other.pid))
            return false;
        if (this.createBy == null) {
            if (other.createBy != null)
                return false;
        }
        else if (!this.createBy.equals(other.createBy))
            return false;
        if (this.createAt == null) {
            if (other.createAt != null)
                return false;
        }
        else if (!this.createAt.equals(other.createAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.rid == null) ? 0 : this.rid.hashCode());
        result = prime * result + ((this.pid == null) ? 0 : this.pid.hashCode());
        result = prime * result + ((this.createBy == null) ? 0 : this.createBy.hashCode());
        result = prime * result + ((this.createAt == null) ? 0 : this.createAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RelRoleRolePojo (");

        sb.append(id);
        sb.append(", ").append(rid);
        sb.append(", ").append(pid);
        sb.append(", ").append(createBy);
        sb.append(", ").append(createAt);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IRelRoleRole from) {
        setId(from.getId());
        setRid(from.getRid());
        setPid(from.getPid());
        setCreateBy(from.getCreateBy());
        setCreateAt(from.getCreateAt());
    }

    @Override
    public <E extends IRelRoleRole> E into(E into) {
        into.from(this);
        return into;
    }
}
