/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.user.repository.generate.tables.pojos;


import java.time.LocalDateTime;

import oceanstars.ecommerce.user.repository.generate.tables.interfaces.IUserResourceType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserResourceTypePojo implements IUserResourceType {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String code;
    private String name;
    private String desc;
    private String href;
    private String method;
    private String body;
    private Boolean enabled;
    private String createBy;
    private LocalDateTime createAt;
    private String updateBy;
    private LocalDateTime updateAt;
    private Integer version;

    public UserResourceTypePojo() {}

    public UserResourceTypePojo(IUserResourceType value) {
        this.id = value.getId();
        this.code = value.getCode();
        this.name = value.getName();
        this.desc = value.getDesc();
        this.href = value.getHref();
        this.method = value.getMethod();
        this.body = value.getBody();
        this.enabled = value.getEnabled();
        this.createBy = value.getCreateBy();
        this.createAt = value.getCreateAt();
        this.updateBy = value.getUpdateBy();
        this.updateAt = value.getUpdateAt();
        this.version = value.getVersion();
    }

    public UserResourceTypePojo(
        Long id,
        String code,
        String name,
        String desc,
        String href,
        String method,
        String body,
        Boolean enabled,
        String createBy,
        LocalDateTime createAt,
        String updateBy,
        LocalDateTime updateAt,
        Integer version
    ) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.desc = desc;
        this.href = href;
        this.method = method;
        this.body = body;
        this.enabled = enabled;
        this.createBy = createBy;
        this.createAt = createAt;
        this.updateBy = updateBy;
        this.updateAt = updateAt;
        this.version = version;
    }

    /**
     * Getter for <code>user_resource_type.id</code>.
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>user_resource_type.id</code>.
     */
    @Override
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>user_resource_type.code</code>.
     */
    @Override
    public String getCode() {
        return this.code;
    }

    /**
     * Setter for <code>user_resource_type.code</code>.
     */
    @Override
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Getter for <code>user_resource_type.name</code>.
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>user_resource_type.name</code>.
     */
    @Override
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>user_resource_type.desc</code>.
     */
    @Override
    public String getDesc() {
        return this.desc;
    }

    /**
     * Setter for <code>user_resource_type.desc</code>.
     */
    @Override
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * Getter for <code>user_resource_type.href</code>.
     */
    @Override
    public String getHref() {
        return this.href;
    }

    /**
     * Setter for <code>user_resource_type.href</code>.
     */
    @Override
    public void setHref(String href) {
        this.href = href;
    }

    /**
     * Getter for <code>user_resource_type.method</code>.
     */
    @Override
    public String getMethod() {
        return this.method;
    }

    /**
     * Setter for <code>user_resource_type.method</code>.
     */
    @Override
    public void setMethod(String method) {
        this.method = method;
    }

    /**
     * Getter for <code>user_resource_type.body</code>.
     */
    @Override
    public String getBody() {
        return this.body;
    }

    /**
     * Setter for <code>user_resource_type.body</code>.
     */
    @Override
    public void setBody(String body) {
        this.body = body;
    }

    /**
     * Getter for <code>user_resource_type.enabled</code>.
     */
    @Override
    public Boolean getEnabled() {
        return this.enabled;
    }

    /**
     * Setter for <code>user_resource_type.enabled</code>.
     */
    @Override
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * Getter for <code>user_resource_type.create_by</code>.
     */
    @Override
    public String getCreateBy() {
        return this.createBy;
    }

    /**
     * Setter for <code>user_resource_type.create_by</code>.
     */
    @Override
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * Getter for <code>user_resource_type.create_at</code>.
     */
    @Override
    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    /**
     * Setter for <code>user_resource_type.create_at</code>.
     */
    @Override
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    /**
     * Getter for <code>user_resource_type.update_by</code>.
     */
    @Override
    public String getUpdateBy() {
        return this.updateBy;
    }

    /**
     * Setter for <code>user_resource_type.update_by</code>.
     */
    @Override
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * Getter for <code>user_resource_type.update_at</code>.
     */
    @Override
    public LocalDateTime getUpdateAt() {
        return this.updateAt;
    }

    /**
     * Setter for <code>user_resource_type.update_at</code>.
     */
    @Override
    public void setUpdateAt(LocalDateTime updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * Getter for <code>user_resource_type.version</code>.
     */
    @Override
    public Integer getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>user_resource_type.version</code>.
     */
    @Override
    public void setVersion(Integer version) {
        this.version = version;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserResourceTypePojo other = (UserResourceTypePojo) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.code == null) {
            if (other.code != null)
                return false;
        }
        else if (!this.code.equals(other.code))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.desc == null) {
            if (other.desc != null)
                return false;
        }
        else if (!this.desc.equals(other.desc))
            return false;
        if (this.href == null) {
            if (other.href != null)
                return false;
        }
        else if (!this.href.equals(other.href))
            return false;
        if (this.method == null) {
            if (other.method != null)
                return false;
        }
        else if (!this.method.equals(other.method))
            return false;
        if (this.body == null) {
            if (other.body != null)
                return false;
        }
        else if (!this.body.equals(other.body))
            return false;
        if (this.enabled == null) {
            if (other.enabled != null)
                return false;
        }
        else if (!this.enabled.equals(other.enabled))
            return false;
        if (this.createBy == null) {
            if (other.createBy != null)
                return false;
        }
        else if (!this.createBy.equals(other.createBy))
            return false;
        if (this.createAt == null) {
            if (other.createAt != null)
                return false;
        }
        else if (!this.createAt.equals(other.createAt))
            return false;
        if (this.updateBy == null) {
            if (other.updateBy != null)
                return false;
        }
        else if (!this.updateBy.equals(other.updateBy))
            return false;
        if (this.updateAt == null) {
            if (other.updateAt != null)
                return false;
        }
        else if (!this.updateAt.equals(other.updateAt))
            return false;
        if (this.version == null) {
            if (other.version != null)
                return false;
        }
        else if (!this.version.equals(other.version))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.code == null) ? 0 : this.code.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.desc == null) ? 0 : this.desc.hashCode());
        result = prime * result + ((this.href == null) ? 0 : this.href.hashCode());
        result = prime * result + ((this.method == null) ? 0 : this.method.hashCode());
        result = prime * result + ((this.body == null) ? 0 : this.body.hashCode());
        result = prime * result + ((this.enabled == null) ? 0 : this.enabled.hashCode());
        result = prime * result + ((this.createBy == null) ? 0 : this.createBy.hashCode());
        result = prime * result + ((this.createAt == null) ? 0 : this.createAt.hashCode());
        result = prime * result + ((this.updateBy == null) ? 0 : this.updateBy.hashCode());
        result = prime * result + ((this.updateAt == null) ? 0 : this.updateAt.hashCode());
        result = prime * result + ((this.version == null) ? 0 : this.version.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserResourceTypePojo (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(name);
        sb.append(", ").append(desc);
        sb.append(", ").append(href);
        sb.append(", ").append(method);
        sb.append(", ").append(body);
        sb.append(", ").append(enabled);
        sb.append(", ").append(createBy);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateBy);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUserResourceType from) {
        setId(from.getId());
        setCode(from.getCode());
        setName(from.getName());
        setDesc(from.getDesc());
        setHref(from.getHref());
        setMethod(from.getMethod());
        setBody(from.getBody());
        setEnabled(from.getEnabled());
        setCreateBy(from.getCreateBy());
        setCreateAt(from.getCreateAt());
        setUpdateBy(from.getUpdateBy());
        setUpdateAt(from.getUpdateAt());
        setVersion(from.getVersion());
    }

    @Override
    public <E extends IUserResourceType> E into(E into) {
        into.from(this);
        return into;
    }
}
