kafka:
  admin:
    bootstrap:
      servers: 10.168.3.54:9092,10.168.3.52:9092,10.168.3.53:9092
  producer:
    bootstrap:
      servers: 10.168.3.54:9092,10.168.3.52:9092,10.168.3.53:9092
    key:
      serializer: org.apache.kafka.common.serialization.StringSerializer
    value:
      serializer: org.apache.kafka.common.serialization.StringSerializer
  consumer:
    bootstrap:
      servers: 10.168.3.54:9092,10.168.3.52:9092,10.168.3.53:9092
    key:
      serializer: org.apache.kafka.common.serialization.StringDeserializer
    value:
      serializer: org.apache.kafka.common.serialization.StringDeserializer
    concurrency: 3
    poll:
      timeout: 3000
  topics:
    sync-cart-pos:
      name: marriott-sync-cart-pos
      partitions: 6
      replicas: 1
    #      compact: true
    #      replicasAssignments:
    #        0:
    #          - 0
    #          - 1
    #        1:
    #          - 2
    #          - 3
    #      configs: { "segment.bytes": "0" ,"segment.ms": "0" }
    callback-order-status:
      name: marriott-callback-order-status
      partitions: 6
      replicas: 1
#      compact: false
#      replicasAssignments:
#        0:
#          - 0
#          - 1
#        1:
#          - 2
#          - 3
#      configs: { "segment.bytes": "1" ,"segment.ms": "1" }