spring:
  application:
    name: message-service-${POD_NAME}
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    pool:
      enabled: off
  profiles:
    include: server,redis,druid,kafka,cache