spring:
  application:
    name: iam-service
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: Asia/Shanghai
  profiles:
    include: common,token,server,redis,grpc #,cache,kafka,elasticsearch