/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.integration.repository.generate.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import oceanstars.ecommerce.integration.repository.generate.DefaultSchema;
import oceanstars.ecommerce.integration.repository.generate.Indexes;
import oceanstars.ecommerce.integration.repository.generate.Keys;
import oceanstars.ecommerce.integration.repository.generate.tables.records.IntegrationServiceRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row13;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IntegrationService extends TableImpl<IntegrationServiceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>integration_service</code>
     */
    public static final IntegrationService INTEGRATION_SERVICE = new IntegrationService();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IntegrationServiceRecord> getRecordType() {
        return IntegrationServiceRecord.class;
    }

    /**
     * The column <code>integration_service.id</code>.
     */
    public final TableField<IntegrationServiceRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>integration_service.code</code>.
     */
    public final TableField<IntegrationServiceRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(14).nullable(false), this, "");

    /**
     * The column <code>integration_service.endpoint</code>.
     */
    public final TableField<IntegrationServiceRecord, String> ENDPOINT = createField(DSL.name("endpoint"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>integration_service.type</code>.
     */
    public final TableField<IntegrationServiceRecord, Short> TYPE = createField(DSL.name("type"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>integration_service.name</code>.
     */
    public final TableField<IntegrationServiceRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>integration_service.retries</code>.
     */
    public final TableField<IntegrationServiceRecord, Short> RETRIES = createField(DSL.name("retries"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field("3", SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>integration_service.connectTimeout</code>.
     */
    public final TableField<IntegrationServiceRecord, Integer> CONNECTTIMEOUT = createField(DSL.name("connectTimeout"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("60000", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>integration_service.authentication</code>.
     */
    public final TableField<IntegrationServiceRecord, Long> AUTHENTICATION = createField(DSL.name("authentication"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>integration_service.create_by</code>.
     */
    public final TableField<IntegrationServiceRecord, String> CREATE_BY = createField(DSL.name("create_by"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>integration_service.create_at</code>.
     */
    public final TableField<IntegrationServiceRecord, LocalDateTime> CREATE_AT = createField(DSL.name("create_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>integration_service.update_by</code>.
     */
    public final TableField<IntegrationServiceRecord, String> UPDATE_BY = createField(DSL.name("update_by"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>integration_service.update_at</code>.
     */
    public final TableField<IntegrationServiceRecord, LocalDateTime> UPDATE_AT = createField(DSL.name("update_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>integration_service.version</code>.
     */
    public final TableField<IntegrationServiceRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "");

    private IntegrationService(Name alias, Table<IntegrationServiceRecord> aliased) {
        this(alias, aliased, null);
    }

    private IntegrationService(Name alias, Table<IntegrationServiceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>integration_service</code> table reference
     */
    public IntegrationService(String alias) {
        this(DSL.name(alias), INTEGRATION_SERVICE);
    }

    /**
     * Create an aliased <code>integration_service</code> table reference
     */
    public IntegrationService(Name alias) {
        this(alias, INTEGRATION_SERVICE);
    }

    /**
     * Create a <code>integration_service</code> table reference
     */
    public IntegrationService() {
        this(DSL.name("integration_service"), null);
    }

    public <O extends Record> IntegrationService(Table<O> child, ForeignKey<O, IntegrationServiceRecord> key) {
        super(child, key, INTEGRATION_SERVICE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_ENDPOINT);
    }

    @Override
    public UniqueKey<IntegrationServiceRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_A;
    }

    @Override
    public List<UniqueKey<IntegrationServiceRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_AB);
    }

    @Override
    public TableField<IntegrationServiceRecord, Integer> getRecordVersion() {
        return VERSION;
    }

    @Override
    public IntegrationService as(String alias) {
        return new IntegrationService(DSL.name(alias), this);
    }

    @Override
    public IntegrationService as(Name alias) {
        return new IntegrationService(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public IntegrationService rename(String name) {
        return new IntegrationService(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IntegrationService rename(Name name) {
        return new IntegrationService(name, null);
    }

    // -------------------------------------------------------------------------
    // Row13 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, String, String, Short, String, Short, Integer, Long, String, LocalDateTime, String, LocalDateTime, Integer> fieldsRow() {
        return (Row13) super.fieldsRow();
    }
}
