/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.integration.repository.generate.tables.records;


import java.time.LocalDateTime;

import oceanstars.ecommerce.integration.repository.generate.tables.IntegrationService;
import oceanstars.ecommerce.integration.repository.generate.tables.interfaces.IIntegrationService;
import oceanstars.ecommerce.integration.repository.generate.tables.pojos.IntegrationServicePojo;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IntegrationServiceRecord extends UpdatableRecordImpl<IntegrationServiceRecord> implements Record13<Long, String, String, Short, String, Short, Integer, Long, String, LocalDateTime, String, LocalDateTime, Integer>, IIntegrationService {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>integration_service.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>integration_service.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>integration_service.code</code>.
     */
    @Override
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>integration_service.code</code>.
     */
    @Override
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>integration_service.endpoint</code>.
     */
    @Override
    public void setEndpoint(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>integration_service.endpoint</code>.
     */
    @Override
    public String getEndpoint() {
        return (String) get(2);
    }

    /**
     * Setter for <code>integration_service.type</code>.
     */
    @Override
    public void setType(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>integration_service.type</code>.
     */
    @Override
    public Short getType() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>integration_service.name</code>.
     */
    @Override
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>integration_service.name</code>.
     */
    @Override
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>integration_service.retries</code>.
     */
    @Override
    public void setRetries(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>integration_service.retries</code>.
     */
    @Override
    public Short getRetries() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>integration_service.connectTimeout</code>.
     */
    @Override
    public void setConnecttimeout(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>integration_service.connectTimeout</code>.
     */
    @Override
    public Integer getConnecttimeout() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>integration_service.authentication</code>.
     */
    @Override
    public void setAuthentication(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>integration_service.authentication</code>.
     */
    @Override
    public Long getAuthentication() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>integration_service.create_by</code>.
     */
    @Override
    public void setCreateBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>integration_service.create_by</code>.
     */
    @Override
    public String getCreateBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>integration_service.create_at</code>.
     */
    @Override
    public void setCreateAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>integration_service.create_at</code>.
     */
    @Override
    public LocalDateTime getCreateAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>integration_service.update_by</code>.
     */
    @Override
    public void setUpdateBy(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>integration_service.update_by</code>.
     */
    @Override
    public String getUpdateBy() {
        return (String) get(10);
    }

    /**
     * Setter for <code>integration_service.update_at</code>.
     */
    @Override
    public void setUpdateAt(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>integration_service.update_at</code>.
     */
    @Override
    public LocalDateTime getUpdateAt() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>integration_service.version</code>.
     */
    @Override
    public void setVersion(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>integration_service.version</code>.
     */
    @Override
    public Integer getVersion() {
        return (Integer) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, String, String, Short, String, Short, Integer, Long, String, LocalDateTime, String, LocalDateTime, Integer> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Long, String, String, Short, String, Short, Integer, Long, String, LocalDateTime, String, LocalDateTime, Integer> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return IntegrationService.INTEGRATION_SERVICE.ID;
    }

    @Override
    public Field<String> field2() {
        return IntegrationService.INTEGRATION_SERVICE.CODE;
    }

    @Override
    public Field<String> field3() {
        return IntegrationService.INTEGRATION_SERVICE.ENDPOINT;
    }

    @Override
    public Field<Short> field4() {
        return IntegrationService.INTEGRATION_SERVICE.TYPE;
    }

    @Override
    public Field<String> field5() {
        return IntegrationService.INTEGRATION_SERVICE.NAME;
    }

    @Override
    public Field<Short> field6() {
        return IntegrationService.INTEGRATION_SERVICE.RETRIES;
    }

    @Override
    public Field<Integer> field7() {
        return IntegrationService.INTEGRATION_SERVICE.CONNECTTIMEOUT;
    }

    @Override
    public Field<Long> field8() {
        return IntegrationService.INTEGRATION_SERVICE.AUTHENTICATION;
    }

    @Override
    public Field<String> field9() {
        return IntegrationService.INTEGRATION_SERVICE.CREATE_BY;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return IntegrationService.INTEGRATION_SERVICE.CREATE_AT;
    }

    @Override
    public Field<String> field11() {
        return IntegrationService.INTEGRATION_SERVICE.UPDATE_BY;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return IntegrationService.INTEGRATION_SERVICE.UPDATE_AT;
    }

    @Override
    public Field<Integer> field13() {
        return IntegrationService.INTEGRATION_SERVICE.VERSION;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCode();
    }

    @Override
    public String component3() {
        return getEndpoint();
    }

    @Override
    public Short component4() {
        return getType();
    }

    @Override
    public String component5() {
        return getName();
    }

    @Override
    public Short component6() {
        return getRetries();
    }

    @Override
    public Integer component7() {
        return getConnecttimeout();
    }

    @Override
    public Long component8() {
        return getAuthentication();
    }

    @Override
    public String component9() {
        return getCreateBy();
    }

    @Override
    public LocalDateTime component10() {
        return getCreateAt();
    }

    @Override
    public String component11() {
        return getUpdateBy();
    }

    @Override
    public LocalDateTime component12() {
        return getUpdateAt();
    }

    @Override
    public Integer component13() {
        return getVersion();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCode();
    }

    @Override
    public String value3() {
        return getEndpoint();
    }

    @Override
    public Short value4() {
        return getType();
    }

    @Override
    public String value5() {
        return getName();
    }

    @Override
    public Short value6() {
        return getRetries();
    }

    @Override
    public Integer value7() {
        return getConnecttimeout();
    }

    @Override
    public Long value8() {
        return getAuthentication();
    }

    @Override
    public String value9() {
        return getCreateBy();
    }

    @Override
    public LocalDateTime value10() {
        return getCreateAt();
    }

    @Override
    public String value11() {
        return getUpdateBy();
    }

    @Override
    public LocalDateTime value12() {
        return getUpdateAt();
    }

    @Override
    public Integer value13() {
        return getVersion();
    }

    @Override
    public IntegrationServiceRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public IntegrationServiceRecord value2(String value) {
        setCode(value);
        return this;
    }

    @Override
    public IntegrationServiceRecord value3(String value) {
        setEndpoint(value);
        return this;
    }

    @Override
    public IntegrationServiceRecord value4(Short value) {
        setType(value);
        return this;
    }

    @Override
    public IntegrationServiceRecord value5(String value) {
        setName(value);
        return this;
    }

    @Override
    public IntegrationServiceRecord value6(Short value) {
        setRetries(value);
        return this;
    }

    @Override
    public IntegrationServiceRecord value7(Integer value) {
        setConnecttimeout(value);
        return this;
    }

    @Override
    public IntegrationServiceRecord value8(Long value) {
        setAuthentication(value);
        return this;
    }

    @Override
    public IntegrationServiceRecord value9(String value) {
        setCreateBy(value);
        return this;
    }

    @Override
    public IntegrationServiceRecord value10(LocalDateTime value) {
        setCreateAt(value);
        return this;
    }

    @Override
    public IntegrationServiceRecord value11(String value) {
        setUpdateBy(value);
        return this;
    }

    @Override
    public IntegrationServiceRecord value12(LocalDateTime value) {
        setUpdateAt(value);
        return this;
    }

    @Override
    public IntegrationServiceRecord value13(Integer value) {
        setVersion(value);
        return this;
    }

    @Override
    public IntegrationServiceRecord values(Long value1, String value2, String value3, Short value4, String value5, Short value6, Integer value7, Long value8, String value9, LocalDateTime value10, String value11, LocalDateTime value12, Integer value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IIntegrationService from) {
        setId(from.getId());
        setCode(from.getCode());
        setEndpoint(from.getEndpoint());
        setType(from.getType());
        setName(from.getName());
        setRetries(from.getRetries());
        setConnecttimeout(from.getConnecttimeout());
        setAuthentication(from.getAuthentication());
        setCreateBy(from.getCreateBy());
        setCreateAt(from.getCreateAt());
        setUpdateBy(from.getUpdateBy());
        setUpdateAt(from.getUpdateAt());
        setVersion(from.getVersion());
    }

    @Override
    public <E extends IIntegrationService> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IntegrationServiceRecord
     */
    public IntegrationServiceRecord() {
        super(IntegrationService.INTEGRATION_SERVICE);
    }

    /**
     * Create a detached, initialised IntegrationServiceRecord
     */
    public IntegrationServiceRecord(Long id, String code, String endpoint, Short type, String name, Short retries, Integer connecttimeout, Long authentication, String createBy, LocalDateTime createAt, String updateBy, LocalDateTime updateAt, Integer version) {
        super(IntegrationService.INTEGRATION_SERVICE);

        setId(id);
        setCode(code);
        setEndpoint(endpoint);
        setType(type);
        setName(name);
        setRetries(retries);
        setConnecttimeout(connecttimeout);
        setAuthentication(authentication);
        setCreateBy(createBy);
        setCreateAt(createAt);
        setUpdateBy(updateBy);
        setUpdateAt(updateAt);
        setVersion(version);
    }

    /**
     * Create a detached, initialised IntegrationServiceRecord
     */
    public IntegrationServiceRecord(IntegrationServicePojo value) {
        super(IntegrationService.INTEGRATION_SERVICE);

        if (value != null) {
            setId(value.getId());
            setCode(value.getCode());
            setEndpoint(value.getEndpoint());
            setType(value.getType());
            setName(value.getName());
            setRetries(value.getRetries());
            setConnecttimeout(value.getConnecttimeout());
            setAuthentication(value.getAuthentication());
            setCreateBy(value.getCreateBy());
            setCreateAt(value.getCreateAt());
            setUpdateBy(value.getUpdateBy());
            setUpdateAt(value.getUpdateAt());
            setVersion(value.getVersion());
        }
    }
}
