/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.integration.repository.generate.tables.records;


import java.time.LocalDateTime;

import oceanstars.ecommerce.integration.repository.generate.tables.IntegrationRoute;
import oceanstars.ecommerce.integration.repository.generate.tables.interfaces.IIntegrationRoute;
import oceanstars.ecommerce.integration.repository.generate.tables.pojos.IntegrationRoutePojo;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IntegrationRouteRecord extends UpdatableRecordImpl<IntegrationRouteRecord> implements Record13<Long, String, String, String, Long, Long, String, String, String, LocalDateTime, String, LocalDateTime, Integer>, IIntegrationRoute {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>integration_route.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>integration_route.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>integration_route.code</code>.
     */
    @Override
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>integration_route.code</code>.
     */
    @Override
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>integration_route.event</code>.
     */
    @Override
    public void setEvent(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>integration_route.event</code>.
     */
    @Override
    public String getEvent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>integration_route.group</code>.
     */
    @Override
    public void setGroup(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>integration_route.group</code>.
     */
    @Override
    public String getGroup() {
        return (String) get(3);
    }

    /**
     * Setter for <code>integration_route.service</code>.
     */
    @Override
    public void setService(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>integration_route.service</code>.
     */
    @Override
    public Long getService() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>integration_route.gateway</code>.
     */
    @Override
    public void setGateway(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>integration_route.gateway</code>.
     */
    @Override
    public Long getGateway() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>integration_route.name</code>.
     */
    @Override
    public void setName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>integration_route.name</code>.
     */
    @Override
    public String getName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>integration_route.description</code>.
     */
    @Override
    public void setDescription(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>integration_route.description</code>.
     */
    @Override
    public String getDescription() {
        return (String) get(7);
    }

    /**
     * Setter for <code>integration_route.create_by</code>.
     */
    @Override
    public void setCreateBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>integration_route.create_by</code>.
     */
    @Override
    public String getCreateBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>integration_route.create_at</code>.
     */
    @Override
    public void setCreateAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>integration_route.create_at</code>.
     */
    @Override
    public LocalDateTime getCreateAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>integration_route.update_by</code>.
     */
    @Override
    public void setUpdateBy(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>integration_route.update_by</code>.
     */
    @Override
    public String getUpdateBy() {
        return (String) get(10);
    }

    /**
     * Setter for <code>integration_route.update_at</code>.
     */
    @Override
    public void setUpdateAt(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>integration_route.update_at</code>.
     */
    @Override
    public LocalDateTime getUpdateAt() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>integration_route.version</code>.
     */
    @Override
    public void setVersion(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>integration_route.version</code>.
     */
    @Override
    public Integer getVersion() {
        return (Integer) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, String, String, String, Long, Long, String, String, String, LocalDateTime, String, LocalDateTime, Integer> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Long, String, String, String, Long, Long, String, String, String, LocalDateTime, String, LocalDateTime, Integer> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return IntegrationRoute.INTEGRATION_ROUTE.ID;
    }

    @Override
    public Field<String> field2() {
        return IntegrationRoute.INTEGRATION_ROUTE.CODE;
    }

    @Override
    public Field<String> field3() {
        return IntegrationRoute.INTEGRATION_ROUTE.EVENT;
    }

    @Override
    public Field<String> field4() {
        return IntegrationRoute.INTEGRATION_ROUTE.GROUP;
    }

    @Override
    public Field<Long> field5() {
        return IntegrationRoute.INTEGRATION_ROUTE.SERVICE;
    }

    @Override
    public Field<Long> field6() {
        return IntegrationRoute.INTEGRATION_ROUTE.GATEWAY;
    }

    @Override
    public Field<String> field7() {
        return IntegrationRoute.INTEGRATION_ROUTE.NAME;
    }

    @Override
    public Field<String> field8() {
        return IntegrationRoute.INTEGRATION_ROUTE.DESCRIPTION;
    }

    @Override
    public Field<String> field9() {
        return IntegrationRoute.INTEGRATION_ROUTE.CREATE_BY;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return IntegrationRoute.INTEGRATION_ROUTE.CREATE_AT;
    }

    @Override
    public Field<String> field11() {
        return IntegrationRoute.INTEGRATION_ROUTE.UPDATE_BY;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return IntegrationRoute.INTEGRATION_ROUTE.UPDATE_AT;
    }

    @Override
    public Field<Integer> field13() {
        return IntegrationRoute.INTEGRATION_ROUTE.VERSION;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCode();
    }

    @Override
    public String component3() {
        return getEvent();
    }

    @Override
    public String component4() {
        return getGroup();
    }

    @Override
    public Long component5() {
        return getService();
    }

    @Override
    public Long component6() {
        return getGateway();
    }

    @Override
    public String component7() {
        return getName();
    }

    @Override
    public String component8() {
        return getDescription();
    }

    @Override
    public String component9() {
        return getCreateBy();
    }

    @Override
    public LocalDateTime component10() {
        return getCreateAt();
    }

    @Override
    public String component11() {
        return getUpdateBy();
    }

    @Override
    public LocalDateTime component12() {
        return getUpdateAt();
    }

    @Override
    public Integer component13() {
        return getVersion();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCode();
    }

    @Override
    public String value3() {
        return getEvent();
    }

    @Override
    public String value4() {
        return getGroup();
    }

    @Override
    public Long value5() {
        return getService();
    }

    @Override
    public Long value6() {
        return getGateway();
    }

    @Override
    public String value7() {
        return getName();
    }

    @Override
    public String value8() {
        return getDescription();
    }

    @Override
    public String value9() {
        return getCreateBy();
    }

    @Override
    public LocalDateTime value10() {
        return getCreateAt();
    }

    @Override
    public String value11() {
        return getUpdateBy();
    }

    @Override
    public LocalDateTime value12() {
        return getUpdateAt();
    }

    @Override
    public Integer value13() {
        return getVersion();
    }

    @Override
    public IntegrationRouteRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public IntegrationRouteRecord value2(String value) {
        setCode(value);
        return this;
    }

    @Override
    public IntegrationRouteRecord value3(String value) {
        setEvent(value);
        return this;
    }

    @Override
    public IntegrationRouteRecord value4(String value) {
        setGroup(value);
        return this;
    }

    @Override
    public IntegrationRouteRecord value5(Long value) {
        setService(value);
        return this;
    }

    @Override
    public IntegrationRouteRecord value6(Long value) {
        setGateway(value);
        return this;
    }

    @Override
    public IntegrationRouteRecord value7(String value) {
        setName(value);
        return this;
    }

    @Override
    public IntegrationRouteRecord value8(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public IntegrationRouteRecord value9(String value) {
        setCreateBy(value);
        return this;
    }

    @Override
    public IntegrationRouteRecord value10(LocalDateTime value) {
        setCreateAt(value);
        return this;
    }

    @Override
    public IntegrationRouteRecord value11(String value) {
        setUpdateBy(value);
        return this;
    }

    @Override
    public IntegrationRouteRecord value12(LocalDateTime value) {
        setUpdateAt(value);
        return this;
    }

    @Override
    public IntegrationRouteRecord value13(Integer value) {
        setVersion(value);
        return this;
    }

    @Override
    public IntegrationRouteRecord values(Long value1, String value2, String value3, String value4, Long value5, Long value6, String value7, String value8, String value9, LocalDateTime value10, String value11, LocalDateTime value12, Integer value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IIntegrationRoute from) {
        setId(from.getId());
        setCode(from.getCode());
        setEvent(from.getEvent());
        setGroup(from.getGroup());
        setService(from.getService());
        setGateway(from.getGateway());
        setName(from.getName());
        setDescription(from.getDescription());
        setCreateBy(from.getCreateBy());
        setCreateAt(from.getCreateAt());
        setUpdateBy(from.getUpdateBy());
        setUpdateAt(from.getUpdateAt());
        setVersion(from.getVersion());
    }

    @Override
    public <E extends IIntegrationRoute> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IntegrationRouteRecord
     */
    public IntegrationRouteRecord() {
        super(IntegrationRoute.INTEGRATION_ROUTE);
    }

    /**
     * Create a detached, initialised IntegrationRouteRecord
     */
    public IntegrationRouteRecord(Long id, String code, String event, String group, Long service, Long gateway, String name, String description, String createBy, LocalDateTime createAt, String updateBy, LocalDateTime updateAt, Integer version) {
        super(IntegrationRoute.INTEGRATION_ROUTE);

        setId(id);
        setCode(code);
        setEvent(event);
        setGroup(group);
        setService(service);
        setGateway(gateway);
        setName(name);
        setDescription(description);
        setCreateBy(createBy);
        setCreateAt(createAt);
        setUpdateBy(updateBy);
        setUpdateAt(updateAt);
        setVersion(version);
    }

    /**
     * Create a detached, initialised IntegrationRouteRecord
     */
    public IntegrationRouteRecord(IntegrationRoutePojo value) {
        super(IntegrationRoute.INTEGRATION_ROUTE);

        if (value != null) {
            setId(value.getId());
            setCode(value.getCode());
            setEvent(value.getEvent());
            setGroup(value.getGroup());
            setService(value.getService());
            setGateway(value.getGateway());
            setName(value.getName());
            setDescription(value.getDescription());
            setCreateBy(value.getCreateBy());
            setCreateAt(value.getCreateAt());
            setUpdateBy(value.getUpdateBy());
            setUpdateAt(value.getUpdateAt());
            setVersion(value.getVersion());
        }
    }
}
