#druid连接池的设置
druid:
  # 特别注意：java 9以后需要将com.mysql.jdbc.Driver  改为  com.mysql.cj.jdbc.Driver即可
  # 否则报错：Loading class `com.mysql.jdbc.Driver'. This is deprecated.
  driver-class-name: com.mysql.cj.jdbc.Driver
  #基本属性
  url: jdbc:mysql://${MYSQL_SERVICE_HOST}:3306/${MYSQL_SERVICE_DB_NAME}?useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
  username: ${MYSQL_SERVICE_USER}
  password: ${MYSQL_SERVICE_PASSWORD}
  #  #初始化时建立物理连接的个数
  initial-size: 5
  #  #最小连接池数量
  min-idle: 5
  #  #最大连接池数量 maxIdle已经不再使用
  max-active: 50
  #  #获取连接时最大等待时间，单位毫秒
  #  max-wait: 60000
  #  #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
  #  test-while-idle: true
  #  #既作为检测的间隔时间又作为testWhileIdel执行的依据
  #  time-between-eviction-runs-millis: 60000
  #  #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
  #  min-evictable-idle-time-millis: 30000
  #  #用来检测连接是否有效的sql 必须是一个查询语句
  #  #mysql中为 select 'x'
  #  #oracle中为 select 1 from dual
  #  validation-query: select 'x'
  #  #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
  #  test-on-borrow: false
  #  #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
  #  test-on-return: false
  #  #当数据库抛出不可恢复的异常时,抛弃该连接
  #  #exception-sorter: true
  #  #是否缓存preparedStatement,mysql5.5+建议开启
  #  #pool-prepared-statements: true
  #  #当值大于0时poolPreparedStatements会自动修改为true
  #  max-pool-prepared-statement-per-connection-size: 20
  #  #配置扩展插件
  filters: stat,wall,log4j2
  #  #通过connectProperties属性来打开mergeSql功能；慢SQL记录
  #  connection-properties: druid.stat.mergeSql=true;ndruid.stat.slowSqlMillis=500
  #  #合并多个DruidDataSource的监控数据
  #  use-global-data-source-stat: true
  #Druid状态跟踪客户端配置
  stat-view-servlet:
    enabled: false
    url-pattern: /druid/*
    #访问控制(deny优先于allow)
    allow: 127.0.0.1
    #允许清空统计数据
    reset-enable: false
  #web跟踪过滤规则配置
  web-stat-filter:
    enabled: false
    url-pattern: /*
    exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"