/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.integration.repository.generate.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IIntegrationAuthentication extends Serializable {

    /**
     * Setter for <code>integration_authentication.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>integration_authentication.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>integration_authentication.appKey</code>.
     */
    public void setAppkey(String value);

    /**
     * Getter for <code>integration_authentication.appKey</code>.
     */
    public String getAppkey();

    /**
     * Setter for <code>integration_authentication.appSecret</code>.
     */
    public void setAppsecret(String value);

    /**
     * Getter for <code>integration_authentication.appSecret</code>.
     */
    public String getAppsecret();

    /**
     * Setter for <code>integration_authentication.x509Certificate</code>.
     */
    public void setX509certificate(byte[] value);

    /**
     * Getter for <code>integration_authentication.x509Certificate</code>.
     */
    public byte[] getX509certificate();

    /**
     * Setter for <code>integration_authentication.create_by</code>.
     */
    public void setCreateBy(String value);

    /**
     * Getter for <code>integration_authentication.create_by</code>.
     */
    public String getCreateBy();

    /**
     * Setter for <code>integration_authentication.create_at</code>.
     */
    public void setCreateAt(LocalDateTime value);

    /**
     * Getter for <code>integration_authentication.create_at</code>.
     */
    public LocalDateTime getCreateAt();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IIntegrationAuthentication
     */
    public void from(IIntegrationAuthentication from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IIntegrationAuthentication
     */
    public <E extends IIntegrationAuthentication> E into(E into);
}
