spring:
  kafka:
    bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
    producer:
      key-serializer: oceanstars.ecommerce.infrastructure.kafka.serialization.KafkaProtobufSerializer
      value-serializer: oceanstars.ecommerce.infrastructure.kafka.serialization.KafkaProtobufSerializer
      properties:
        interceptor.classes: oceanstars.ecommerce.infrastructure.kafka.interceptor.Producer4SessionInterceptor
    consumer:
      key-deserializer: oceanstars.ecommerce.infrastructure.kafka.serialization.KafkaProtobufDeserializer
      value-deserializer: oceanstars.ecommerce.infrastructure.kafka.serialization.KafkaProtobufDeserializer
      enable-auto-commit: false
      auto-offset-reset: latest
    listener:
      concurrency: 3
      ack-mode: MANUAL_IMMEDIATE
    topics:
      - name: oceanstars.notification.user.resource-type.created
        partitions: 3
        replicas: 2
        compact: true
        replicasAssignments:
          "0":
            - 0
            - 1
          "1":
            - 1
            - 2
          "2":
            - 2
            - 0
#        configs: { "segment.bytes": "0" ,"segment.ms": "0" }
      - name: oceanstars.notification.user.role.created
        partitions: 3
        replicas: 2
        compact: false
        replicasAssignments:
          "0":
            - 0
            - 1
          "1":
            - 1
            - 2
          "2":
            - 2
            - 0
#        configs: { "segment.bytes": "0" ,"segment.ms": "0" }