/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.integration.repository.generate;


import java.util.Arrays;
import java.util.List;

import oceanstars.ecommerce.integration.repository.generate.tables.IntegrationAuthentication;
import oceanstars.ecommerce.integration.repository.generate.tables.IntegrationGateway;
import oceanstars.ecommerce.integration.repository.generate.tables.IntegrationRoute;
import oceanstars.ecommerce.integration.repository.generate.tables.IntegrationService;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>integration_authentication</code>.
     */
    public final IntegrationAuthentication INTEGRATION_AUTHENTICATION = IntegrationAuthentication.INTEGRATION_AUTHENTICATION;

    /**
     * The table <code>integration_gateway</code>.
     */
    public final IntegrationGateway INTEGRATION_GATEWAY = IntegrationGateway.INTEGRATION_GATEWAY;

    /**
     * The table <code>integration_route</code>.
     */
    public final IntegrationRoute INTEGRATION_ROUTE = IntegrationRoute.INTEGRATION_ROUTE;

    /**
     * The table <code>integration_service</code>.
     */
    public final IntegrationService INTEGRATION_SERVICE = IntegrationService.INTEGRATION_SERVICE;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            IntegrationAuthentication.INTEGRATION_AUTHENTICATION,
            IntegrationGateway.INTEGRATION_GATEWAY,
            IntegrationRoute.INTEGRATION_ROUTE,
            IntegrationService.INTEGRATION_SERVICE
        );
    }
}
