/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.integration.repository.generate;


import oceanstars.ecommerce.integration.repository.generate.tables.IntegrationAuthentication;
import oceanstars.ecommerce.integration.repository.generate.tables.IntegrationRoute;
import oceanstars.ecommerce.integration.repository.generate.tables.IntegrationService;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_APPKEY = Internal.createIndex(DSL.name("idx_appKey"), IntegrationAuthentication.INTEGRATION_AUTHENTICATION, new OrderField[] { IntegrationAuthentication.INTEGRATION_AUTHENTICATION.APPKEY }, true);
    public static final Index IDX_ENDPOINT = Internal.createIndex(DSL.name("idx_endpoint"), IntegrationService.INTEGRATION_SERVICE, new OrderField[] { IntegrationService.INTEGRATION_SERVICE.ENDPOINT }, true);
    public static final Index IDX_EVENT = Internal.createIndex(DSL.name("idx_event"), IntegrationRoute.INTEGRATION_ROUTE, new OrderField[] { IntegrationRoute.INTEGRATION_ROUTE.EVENT }, false);
    public static final Index IDX_GATEWAY = Internal.createIndex(DSL.name("idx_gateway"), IntegrationRoute.INTEGRATION_ROUTE, new OrderField[] { IntegrationRoute.INTEGRATION_ROUTE.GATEWAY }, false);
    public static final Index IDX_GROUP = Internal.createIndex(DSL.name("idx_group"), IntegrationRoute.INTEGRATION_ROUTE, new OrderField[] { IntegrationRoute.INTEGRATION_ROUTE.GROUP }, false);
    public static final Index IDX_ROUTE = Internal.createIndex(DSL.name("idx_route"), IntegrationRoute.INTEGRATION_ROUTE, new OrderField[] { IntegrationRoute.INTEGRATION_ROUTE.EVENT, IntegrationRoute.INTEGRATION_ROUTE.GROUP }, true);
    public static final Index IDX_SERVICE = Internal.createIndex(DSL.name("idx_service"), IntegrationRoute.INTEGRATION_ROUTE, new OrderField[] { IntegrationRoute.INTEGRATION_ROUTE.SERVICE }, false);
}
