/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.integration.repository.generate;


import oceanstars.ecommerce.integration.repository.generate.tables.IntegrationAuthentication;
import oceanstars.ecommerce.integration.repository.generate.tables.IntegrationGateway;
import oceanstars.ecommerce.integration.repository.generate.tables.IntegrationRoute;
import oceanstars.ecommerce.integration.repository.generate.tables.IntegrationService;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>integration_authentication</code>.
     */
    public static final IntegrationAuthentication INTEGRATION_AUTHENTICATION = IntegrationAuthentication.INTEGRATION_AUTHENTICATION;

    /**
     * The table <code>integration_gateway</code>.
     */
    public static final IntegrationGateway INTEGRATION_GATEWAY = IntegrationGateway.INTEGRATION_GATEWAY;

    /**
     * The table <code>integration_route</code>.
     */
    public static final IntegrationRoute INTEGRATION_ROUTE = IntegrationRoute.INTEGRATION_ROUTE;

    /**
     * The table <code>integration_service</code>.
     */
    public static final IntegrationService INTEGRATION_SERVICE = IntegrationService.INTEGRATION_SERVICE;
}
