/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.user.repository.generate.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import oceanstars.ecommerce.user.repository.generate.DefaultSchema;
import oceanstars.ecommerce.user.repository.generate.Indexes;
import oceanstars.ecommerce.user.repository.generate.Keys;
import oceanstars.ecommerce.user.repository.generate.tables.records.RelRoleRoleRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RelRoleRole extends TableImpl<RelRoleRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rel_role_role</code>
     */
    public static final RelRoleRole REL_ROLE_ROLE = new RelRoleRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RelRoleRoleRecord> getRecordType() {
        return RelRoleRoleRecord.class;
    }

    /**
     * The column <code>rel_role_role.id</code>.
     */
    public final TableField<RelRoleRoleRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>rel_role_role.rid</code>.
     */
    public final TableField<RelRoleRoleRecord, Long> RID = createField(DSL.name("rid"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>rel_role_role.pid</code>.
     */
    public final TableField<RelRoleRoleRecord, Long> PID = createField(DSL.name("pid"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>rel_role_role.create_by</code>.
     */
    public final TableField<RelRoleRoleRecord, String> CREATE_BY = createField(DSL.name("create_by"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>rel_role_role.create_at</code>.
     */
    public final TableField<RelRoleRoleRecord, LocalDateTime> CREATE_AT = createField(DSL.name("create_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private RelRoleRole(Name alias, Table<RelRoleRoleRecord> aliased) {
        this(alias, aliased, null);
    }

    private RelRoleRole(Name alias, Table<RelRoleRoleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>rel_role_role</code> table reference
     */
    public RelRoleRole(String alias) {
        this(DSL.name(alias), REL_ROLE_ROLE);
    }

    /**
     * Create an aliased <code>rel_role_role</code> table reference
     */
    public RelRoleRole(Name alias) {
        this(alias, REL_ROLE_ROLE);
    }

    /**
     * Create a <code>rel_role_role</code> table reference
     */
    public RelRoleRole() {
        this(DSL.name("rel_role_role"), null);
    }

    public <O extends Record> RelRoleRole(Table<O> child, ForeignKey<O, RelRoleRoleRecord> key) {
        super(child, key, REL_ROLE_ROLE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_REL_ROLE_PID, Indexes.IDX_REL_ROLE_RID);
    }

    @Override
    public UniqueKey<RelRoleRoleRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_C;
    }

    @Override
    public List<UniqueKey<RelRoleRoleRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.IDX_REL_ROLE);
    }

    @Override
    public RelRoleRole as(String alias) {
        return new RelRoleRole(DSL.name(alias), this);
    }

    @Override
    public RelRoleRole as(Name alias) {
        return new RelRoleRole(alias, this);
    }

    @Override
    public RelRoleRole as(Table<?> alias) {
        return new RelRoleRole(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RelRoleRole rename(String name) {
        return new RelRoleRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RelRoleRole rename(Name name) {
        return new RelRoleRole(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RelRoleRole rename(Table<?> name) {
        return new RelRoleRole(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, Long, String, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super Long, ? super Long, ? super Long, ? super String, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super Long, ? super Long, ? super Long, ? super String, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
