/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.user.repository.generate.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import oceanstars.ecommerce.user.repository.generate.DefaultSchema;
import oceanstars.ecommerce.user.repository.generate.Indexes;
import oceanstars.ecommerce.user.repository.generate.Keys;
import oceanstars.ecommerce.user.repository.generate.tables.records.RelRolePermissionRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RelRolePermission extends TableImpl<RelRolePermissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rel_role_permission</code>
     */
    public static final RelRolePermission REL_ROLE_PERMISSION = new RelRolePermission();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RelRolePermissionRecord> getRecordType() {
        return RelRolePermissionRecord.class;
    }

    /**
     * The column <code>rel_role_permission.id</code>.
     */
    public final TableField<RelRolePermissionRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>rel_role_permission.rid</code>.
     */
    public final TableField<RelRolePermissionRecord, Long> RID = createField(DSL.name("rid"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>rel_role_permission.pid</code>.
     */
    public final TableField<RelRolePermissionRecord, Long> PID = createField(DSL.name("pid"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>rel_role_permission.create_by</code>.
     */
    public final TableField<RelRolePermissionRecord, String> CREATE_BY = createField(DSL.name("create_by"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>rel_role_permission.create_at</code>.
     */
    public final TableField<RelRolePermissionRecord, LocalDateTime> CREATE_AT = createField(DSL.name("create_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private RelRolePermission(Name alias, Table<RelRolePermissionRecord> aliased) {
        this(alias, aliased, null);
    }

    private RelRolePermission(Name alias, Table<RelRolePermissionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>rel_role_permission</code> table reference
     */
    public RelRolePermission(String alias) {
        this(DSL.name(alias), REL_ROLE_PERMISSION);
    }

    /**
     * Create an aliased <code>rel_role_permission</code> table reference
     */
    public RelRolePermission(Name alias) {
        this(alias, REL_ROLE_PERMISSION);
    }

    /**
     * Create a <code>rel_role_permission</code> table reference
     */
    public RelRolePermission() {
        this(DSL.name("rel_role_permission"), null);
    }

    public <O extends Record> RelRolePermission(Table<O> child, ForeignKey<O, RelRolePermissionRecord> key) {
        super(child, key, REL_ROLE_PERMISSION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_REL_ROLE_PERM_PID, Indexes.IDX_REL_ROLE_PERM_RID);
    }

    @Override
    public UniqueKey<RelRolePermissionRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_9;
    }

    @Override
    public List<UniqueKey<RelRolePermissionRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.IDX_REL_ROLE_PERM);
    }

    @Override
    public RelRolePermission as(String alias) {
        return new RelRolePermission(DSL.name(alias), this);
    }

    @Override
    public RelRolePermission as(Name alias) {
        return new RelRolePermission(alias, this);
    }

    @Override
    public RelRolePermission as(Table<?> alias) {
        return new RelRolePermission(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RelRolePermission rename(String name) {
        return new RelRolePermission(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RelRolePermission rename(Name name) {
        return new RelRolePermission(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RelRolePermission rename(Table<?> name) {
        return new RelRolePermission(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, Long, String, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super Long, ? super Long, ? super Long, ? super String, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super Long, ? super Long, ? super Long, ? super String, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
