/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.user.repository.generate.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import oceanstars.ecommerce.user.repository.generate.DefaultSchema;
import oceanstars.ecommerce.user.repository.generate.Keys;
import oceanstars.ecommerce.user.repository.generate.tables.records.UserPermissionOperationRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function10;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserPermissionOperation extends TableImpl<UserPermissionOperationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>user_permission_operation</code>
     */
    public static final UserPermissionOperation USER_PERMISSION_OPERATION = new UserPermissionOperation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserPermissionOperationRecord> getRecordType() {
        return UserPermissionOperationRecord.class;
    }

    /**
     * The column <code>user_permission_operation.id</code>.
     */
    public final TableField<UserPermissionOperationRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>user_permission_operation.code</code>.
     */
    public final TableField<UserPermissionOperationRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(12).nullable(false), this, "");

    /**
     * The column <code>user_permission_operation.behavior</code>.
     */
    public final TableField<UserPermissionOperationRecord, String> BEHAVIOR = createField(DSL.name("behavior"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>user_permission_operation.desc</code>.
     */
    public final TableField<UserPermissionOperationRecord, String> DESC = createField(DSL.name("desc"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>user_permission_operation.enabled</code>.
     */
    public final TableField<UserPermissionOperationRecord, Boolean> ENABLED = createField(DSL.name("enabled"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("1", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>user_permission_operation.create_by</code>.
     */
    public final TableField<UserPermissionOperationRecord, String> CREATE_BY = createField(DSL.name("create_by"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>user_permission_operation.create_at</code>.
     */
    public final TableField<UserPermissionOperationRecord, LocalDateTime> CREATE_AT = createField(DSL.name("create_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>user_permission_operation.update_by</code>.
     */
    public final TableField<UserPermissionOperationRecord, String> UPDATE_BY = createField(DSL.name("update_by"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>user_permission_operation.update_at</code>.
     */
    public final TableField<UserPermissionOperationRecord, LocalDateTime> UPDATE_AT = createField(DSL.name("update_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>user_permission_operation.version</code>.
     */
    public final TableField<UserPermissionOperationRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("1", SQLDataType.INTEGER)), this, "");

    private UserPermissionOperation(Name alias, Table<UserPermissionOperationRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserPermissionOperation(Name alias, Table<UserPermissionOperationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>user_permission_operation</code> table reference
     */
    public UserPermissionOperation(String alias) {
        this(DSL.name(alias), USER_PERMISSION_OPERATION);
    }

    /**
     * Create an aliased <code>user_permission_operation</code> table reference
     */
    public UserPermissionOperation(Name alias) {
        this(alias, USER_PERMISSION_OPERATION);
    }

    /**
     * Create a <code>user_permission_operation</code> table reference
     */
    public UserPermissionOperation() {
        this(DSL.name("user_permission_operation"), null);
    }

    public <O extends Record> UserPermissionOperation(Table<O> child, ForeignKey<O, UserPermissionOperationRecord> key) {
        super(child, key, USER_PERMISSION_OPERATION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<UserPermissionOperationRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_5;
    }

    @Override
    public List<UniqueKey<UserPermissionOperationRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.IDX_OPT_IDENTIFIER, Keys.IDX_OPERATION);
    }

    @Override
    public TableField<UserPermissionOperationRecord, Integer> getRecordVersion() {
        return VERSION;
    }

    @Override
    public UserPermissionOperation as(String alias) {
        return new UserPermissionOperation(DSL.name(alias), this);
    }

    @Override
    public UserPermissionOperation as(Name alias) {
        return new UserPermissionOperation(alias, this);
    }

    @Override
    public UserPermissionOperation as(Table<?> alias) {
        return new UserPermissionOperation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserPermissionOperation rename(String name) {
        return new UserPermissionOperation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserPermissionOperation rename(Name name) {
        return new UserPermissionOperation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserPermissionOperation rename(Table<?> name) {
        return new UserPermissionOperation(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, String, String, Boolean, String, LocalDateTime, String, LocalDateTime, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function10<? super Long, ? super String, ? super String, ? super String, ? super Boolean, ? super String, ? super LocalDateTime, ? super String, ? super LocalDateTime, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function10<? super Long, ? super String, ? super String, ? super String, ? super Boolean, ? super String, ? super LocalDateTime, ? super String, ? super LocalDateTime, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
