/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.user.repository.generate.tables.daos;


import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import oceanstars.ecommerce.user.repository.generate.tables.RelRoleRole;
import oceanstars.ecommerce.user.repository.generate.tables.pojos.RelRoleRolePojo;
import oceanstars.ecommerce.user.repository.generate.tables.records.RelRoleRoleRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class RelRoleRoleDao extends DAOImpl<RelRoleRoleRecord, RelRoleRolePojo, Long> {

    /**
     * Create a new RelRoleRoleDao without any configuration
     */
    public RelRoleRoleDao() {
        super(RelRoleRole.REL_ROLE_ROLE, RelRoleRolePojo.class);
    }

    /**
     * Create a new RelRoleRoleDao with an attached configuration
     */
    @Autowired
    public RelRoleRoleDao(Configuration configuration) {
        super(RelRoleRole.REL_ROLE_ROLE, RelRoleRolePojo.class, configuration);
    }

    @Override
    public Long getId(RelRoleRolePojo object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<RelRoleRolePojo> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(RelRoleRole.REL_ROLE_ROLE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<RelRoleRolePojo> fetchById(Long... values) {
        return fetch(RelRoleRole.REL_ROLE_ROLE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public RelRoleRolePojo fetchOneById(Long value) {
        return fetchOne(RelRoleRole.REL_ROLE_ROLE.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<RelRoleRolePojo> fetchOptionalById(Long value) {
        return fetchOptional(RelRoleRole.REL_ROLE_ROLE.ID, value);
    }

    /**
     * Fetch records that have <code>rid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<RelRoleRolePojo> fetchRangeOfRid(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(RelRoleRole.REL_ROLE_ROLE.RID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>rid IN (values)</code>
     */
    public List<RelRoleRolePojo> fetchByRid(Long... values) {
        return fetch(RelRoleRole.REL_ROLE_ROLE.RID, values);
    }

    /**
     * Fetch records that have <code>pid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<RelRoleRolePojo> fetchRangeOfPid(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(RelRoleRole.REL_ROLE_ROLE.PID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>pid IN (values)</code>
     */
    public List<RelRoleRolePojo> fetchByPid(Long... values) {
        return fetch(RelRoleRole.REL_ROLE_ROLE.PID, values);
    }

    /**
     * Fetch records that have <code>create_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<RelRoleRolePojo> fetchRangeOfCreateBy(String lowerInclusive, String upperInclusive) {
        return fetchRange(RelRoleRole.REL_ROLE_ROLE.CREATE_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_by IN (values)</code>
     */
    public List<RelRoleRolePojo> fetchByCreateBy(String... values) {
        return fetch(RelRoleRole.REL_ROLE_ROLE.CREATE_BY, values);
    }

    /**
     * Fetch records that have <code>create_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<RelRoleRolePojo> fetchRangeOfCreateAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(RelRoleRole.REL_ROLE_ROLE.CREATE_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_at IN (values)</code>
     */
    public List<RelRoleRolePojo> fetchByCreateAt(LocalDateTime... values) {
        return fetch(RelRoleRole.REL_ROLE_ROLE.CREATE_AT, values);
    }
}
