spring:
  application:
    name: ecm-service
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: Asia/Shanghai
  profiles:
    include: server,redis,mysql
grpc:
  #  server:
  #    in-process-name: ecm-grpc
  client:
    content:
      address: localhost:9090
