spring:
  application:
    name: ecm-service
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: Asia/Shanghai
  profiles:
    include: server,redis,mysql,cache,kafka,elasticsearch