/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.integration.repository.generate.tables.pojos;


import java.time.LocalDateTime;

import oceanstars.ecommerce.integration.repository.generate.tables.interfaces.IIntegrationService;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IntegrationServicePojo implements IIntegrationService {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        code;
    private String        endpoint;
    private Short         type;
    private String        name;
    private Short         retries;
    private Integer       connecttimeout;
    private Long          authentication;
    private String        createBy;
    private LocalDateTime createAt;
    private String        updateBy;
    private LocalDateTime updateAt;
    private Integer       version;

    public IntegrationServicePojo() {}

    public IntegrationServicePojo(IIntegrationService value) {
        this.id = value.getId();
        this.code = value.getCode();
        this.endpoint = value.getEndpoint();
        this.type = value.getType();
        this.name = value.getName();
        this.retries = value.getRetries();
        this.connecttimeout = value.getConnecttimeout();
        this.authentication = value.getAuthentication();
        this.createBy = value.getCreateBy();
        this.createAt = value.getCreateAt();
        this.updateBy = value.getUpdateBy();
        this.updateAt = value.getUpdateAt();
        this.version = value.getVersion();
    }

    public IntegrationServicePojo(
        Long          id,
        String        code,
        String        endpoint,
        Short         type,
        String        name,
        Short         retries,
        Integer       connecttimeout,
        Long          authentication,
        String        createBy,
        LocalDateTime createAt,
        String        updateBy,
        LocalDateTime updateAt,
        Integer       version
    ) {
        this.id = id;
        this.code = code;
        this.endpoint = endpoint;
        this.type = type;
        this.name = name;
        this.retries = retries;
        this.connecttimeout = connecttimeout;
        this.authentication = authentication;
        this.createBy = createBy;
        this.createAt = createAt;
        this.updateBy = updateBy;
        this.updateAt = updateAt;
        this.version = version;
    }

    /**
     * Getter for <code>integration_service.id</code>.
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>integration_service.id</code>.
     */
    @Override
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>integration_service.code</code>.
     */
    @Override
    public String getCode() {
        return this.code;
    }

    /**
     * Setter for <code>integration_service.code</code>.
     */
    @Override
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Getter for <code>integration_service.endpoint</code>.
     */
    @Override
    public String getEndpoint() {
        return this.endpoint;
    }

    /**
     * Setter for <code>integration_service.endpoint</code>.
     */
    @Override
    public void setEndpoint(String endpoint) {
        this.endpoint = endpoint;
    }

    /**
     * Getter for <code>integration_service.type</code>.
     */
    @Override
    public Short getType() {
        return this.type;
    }

    /**
     * Setter for <code>integration_service.type</code>.
     */
    @Override
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * Getter for <code>integration_service.name</code>.
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>integration_service.name</code>.
     */
    @Override
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>integration_service.retries</code>.
     */
    @Override
    public Short getRetries() {
        return this.retries;
    }

    /**
     * Setter for <code>integration_service.retries</code>.
     */
    @Override
    public void setRetries(Short retries) {
        this.retries = retries;
    }

    /**
     * Getter for <code>integration_service.connectTimeout</code>.
     */
    @Override
    public Integer getConnecttimeout() {
        return this.connecttimeout;
    }

    /**
     * Setter for <code>integration_service.connectTimeout</code>.
     */
    @Override
    public void setConnecttimeout(Integer connecttimeout) {
        this.connecttimeout = connecttimeout;
    }

    /**
     * Getter for <code>integration_service.authentication</code>.
     */
    @Override
    public Long getAuthentication() {
        return this.authentication;
    }

    /**
     * Setter for <code>integration_service.authentication</code>.
     */
    @Override
    public void setAuthentication(Long authentication) {
        this.authentication = authentication;
    }

    /**
     * Getter for <code>integration_service.create_by</code>.
     */
    @Override
    public String getCreateBy() {
        return this.createBy;
    }

    /**
     * Setter for <code>integration_service.create_by</code>.
     */
    @Override
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * Getter for <code>integration_service.create_at</code>.
     */
    @Override
    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    /**
     * Setter for <code>integration_service.create_at</code>.
     */
    @Override
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    /**
     * Getter for <code>integration_service.update_by</code>.
     */
    @Override
    public String getUpdateBy() {
        return this.updateBy;
    }

    /**
     * Setter for <code>integration_service.update_by</code>.
     */
    @Override
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * Getter for <code>integration_service.update_at</code>.
     */
    @Override
    public LocalDateTime getUpdateAt() {
        return this.updateAt;
    }

    /**
     * Setter for <code>integration_service.update_at</code>.
     */
    @Override
    public void setUpdateAt(LocalDateTime updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * Getter for <code>integration_service.version</code>.
     */
    @Override
    public Integer getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>integration_service.version</code>.
     */
    @Override
    public void setVersion(Integer version) {
        this.version = version;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("IntegrationServicePojo (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(endpoint);
        sb.append(", ").append(type);
        sb.append(", ").append(name);
        sb.append(", ").append(retries);
        sb.append(", ").append(connecttimeout);
        sb.append(", ").append(authentication);
        sb.append(", ").append(createBy);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateBy);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IIntegrationService from) {
        setId(from.getId());
        setCode(from.getCode());
        setEndpoint(from.getEndpoint());
        setType(from.getType());
        setName(from.getName());
        setRetries(from.getRetries());
        setConnecttimeout(from.getConnecttimeout());
        setAuthentication(from.getAuthentication());
        setCreateBy(from.getCreateBy());
        setCreateAt(from.getCreateAt());
        setUpdateBy(from.getUpdateBy());
        setUpdateAt(from.getUpdateAt());
        setVersion(from.getVersion());
    }

    @Override
    public <E extends IIntegrationService> E into(E into) {
        into.from(this);
        return into;
    }
}
