/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.integration.repository.generate.tables.pojos;


import java.time.LocalDateTime;

import oceanstars.ecommerce.integration.repository.generate.tables.interfaces.IIntegrationGateway;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IntegrationGatewayPojo implements IIntegrationGateway {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        code;
    private Short         system;
    private String        description;
    private String        createBy;
    private LocalDateTime createAt;
    private String        updateBy;
    private LocalDateTime updateAt;
    private Integer       version;

    public IntegrationGatewayPojo() {}

    public IntegrationGatewayPojo(IIntegrationGateway value) {
        this.id = value.getId();
        this.code = value.getCode();
        this.system = value.getSystem();
        this.description = value.getDescription();
        this.createBy = value.getCreateBy();
        this.createAt = value.getCreateAt();
        this.updateBy = value.getUpdateBy();
        this.updateAt = value.getUpdateAt();
        this.version = value.getVersion();
    }

    public IntegrationGatewayPojo(
        Long          id,
        String        code,
        Short         system,
        String        description,
        String        createBy,
        LocalDateTime createAt,
        String        updateBy,
        LocalDateTime updateAt,
        Integer       version
    ) {
        this.id = id;
        this.code = code;
        this.system = system;
        this.description = description;
        this.createBy = createBy;
        this.createAt = createAt;
        this.updateBy = updateBy;
        this.updateAt = updateAt;
        this.version = version;
    }

    /**
     * Getter for <code>integration_gateway.id</code>.
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>integration_gateway.id</code>.
     */
    @Override
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>integration_gateway.code</code>.
     */
    @Override
    public String getCode() {
        return this.code;
    }

    /**
     * Setter for <code>integration_gateway.code</code>.
     */
    @Override
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Getter for <code>integration_gateway.system</code>.
     */
    @Override
    public Short getSystem() {
        return this.system;
    }

    /**
     * Setter for <code>integration_gateway.system</code>.
     */
    @Override
    public void setSystem(Short system) {
        this.system = system;
    }

    /**
     * Getter for <code>integration_gateway.description</code>.
     */
    @Override
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>integration_gateway.description</code>.
     */
    @Override
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>integration_gateway.create_by</code>.
     */
    @Override
    public String getCreateBy() {
        return this.createBy;
    }

    /**
     * Setter for <code>integration_gateway.create_by</code>.
     */
    @Override
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * Getter for <code>integration_gateway.create_at</code>.
     */
    @Override
    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    /**
     * Setter for <code>integration_gateway.create_at</code>.
     */
    @Override
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    /**
     * Getter for <code>integration_gateway.update_by</code>.
     */
    @Override
    public String getUpdateBy() {
        return this.updateBy;
    }

    /**
     * Setter for <code>integration_gateway.update_by</code>.
     */
    @Override
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * Getter for <code>integration_gateway.update_at</code>.
     */
    @Override
    public LocalDateTime getUpdateAt() {
        return this.updateAt;
    }

    /**
     * Setter for <code>integration_gateway.update_at</code>.
     */
    @Override
    public void setUpdateAt(LocalDateTime updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * Getter for <code>integration_gateway.version</code>.
     */
    @Override
    public Integer getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>integration_gateway.version</code>.
     */
    @Override
    public void setVersion(Integer version) {
        this.version = version;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("IntegrationGatewayPojo (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(system);
        sb.append(", ").append(description);
        sb.append(", ").append(createBy);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateBy);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IIntegrationGateway from) {
        setId(from.getId());
        setCode(from.getCode());
        setSystem(from.getSystem());
        setDescription(from.getDescription());
        setCreateBy(from.getCreateBy());
        setCreateAt(from.getCreateAt());
        setUpdateBy(from.getUpdateBy());
        setUpdateAt(from.getUpdateAt());
        setVersion(from.getVersion());
    }

    @Override
    public <E extends IIntegrationGateway> E into(E into) {
        into.from(this);
        return into;
    }
}
