/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.user.repository.generate.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IRelPermissionResource extends Serializable {

    /**
     * Setter for <code>rel_permission_resource.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>rel_permission_resource.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>rel_permission_resource.pid</code>.
     */
    public void setPid(Long value);

    /**
     * Getter for <code>rel_permission_resource.pid</code>.
     */
    public Long getPid();

    /**
     * Setter for <code>rel_permission_resource.rid</code>.
     */
    public void setRid(Long value);

    /**
     * Getter for <code>rel_permission_resource.rid</code>.
     */
    public Long getRid();

    /**
     * Setter for <code>rel_permission_resource.tid</code>.
     */
    public void setTid(Long value);

    /**
     * Getter for <code>rel_permission_resource.tid</code>.
     */
    public Long getTid();

    /**
     * Setter for <code>rel_permission_resource.oid</code>.
     */
    public void setOid(Long value);

    /**
     * Getter for <code>rel_permission_resource.oid</code>.
     */
    public Long getOid();

    /**
     * Setter for <code>rel_permission_resource.create_by</code>.
     */
    public void setCreateBy(String value);

    /**
     * Getter for <code>rel_permission_resource.create_by</code>.
     */
    public String getCreateBy();

    /**
     * Setter for <code>rel_permission_resource.create_at</code>.
     */
    public void setCreateAt(LocalDateTime value);

    /**
     * Getter for <code>rel_permission_resource.create_at</code>.
     */
    public LocalDateTime getCreateAt();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IRelPermissionResource
     */
    public void from(IRelPermissionResource from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IRelPermissionResource
     */
    public <E extends IRelPermissionResource> E into(E into);
}
