/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.user.repository.generate.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IRelRolePermission extends Serializable {

    /**
     * Setter for <code>rel_role_permission.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>rel_role_permission.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>rel_role_permission.rid</code>.
     */
    public void setRid(Long value);

    /**
     * Getter for <code>rel_role_permission.rid</code>.
     */
    public Long getRid();

    /**
     * Setter for <code>rel_role_permission.pid</code>.
     */
    public void setPid(Long value);

    /**
     * Getter for <code>rel_role_permission.pid</code>.
     */
    public Long getPid();

    /**
     * Setter for <code>rel_role_permission.create_by</code>.
     */
    public void setCreateBy(String value);

    /**
     * Getter for <code>rel_role_permission.create_by</code>.
     */
    public String getCreateBy();

    /**
     * Setter for <code>rel_role_permission.create_at</code>.
     */
    public void setCreateAt(LocalDateTime value);

    /**
     * Getter for <code>rel_role_permission.create_at</code>.
     */
    public LocalDateTime getCreateAt();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IRelRolePermission
     */
    public void from(IRelRolePermission from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IRelRolePermission
     */
    public <E extends IRelRolePermission> E into(E into);
}
