/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.user.repository.generate.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IUserResourceType extends Serializable {

    /**
     * Setter for <code>user_resource_type.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>user_resource_type.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>user_resource_type.code</code>.
     */
    public void setCode(String value);

    /**
     * Getter for <code>user_resource_type.code</code>.
     */
    public String getCode();

    /**
     * Setter for <code>user_resource_type.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>user_resource_type.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>user_resource_type.desc</code>.
     */
    public void setDesc(String value);

    /**
     * Getter for <code>user_resource_type.desc</code>.
     */
    public String getDesc();

    /**
     * Setter for <code>user_resource_type.href</code>.
     */
    public void setHref(String value);

    /**
     * Getter for <code>user_resource_type.href</code>.
     */
    public String getHref();

    /**
     * Setter for <code>user_resource_type.method</code>.
     */
    public void setMethod(String value);

    /**
     * Getter for <code>user_resource_type.method</code>.
     */
    public String getMethod();

    /**
     * Setter for <code>user_resource_type.body</code>.
     */
    public void setBody(String value);

    /**
     * Getter for <code>user_resource_type.body</code>.
     */
    public String getBody();

    /**
     * Setter for <code>user_resource_type.enabled</code>.
     */
    public void setEnabled(Boolean value);

    /**
     * Getter for <code>user_resource_type.enabled</code>.
     */
    public Boolean getEnabled();

    /**
     * Setter for <code>user_resource_type.create_by</code>.
     */
    public void setCreateBy(String value);

    /**
     * Getter for <code>user_resource_type.create_by</code>.
     */
    public String getCreateBy();

    /**
     * Setter for <code>user_resource_type.create_at</code>.
     */
    public void setCreateAt(LocalDateTime value);

    /**
     * Getter for <code>user_resource_type.create_at</code>.
     */
    public LocalDateTime getCreateAt();

    /**
     * Setter for <code>user_resource_type.update_by</code>.
     */
    public void setUpdateBy(String value);

    /**
     * Getter for <code>user_resource_type.update_by</code>.
     */
    public String getUpdateBy();

    /**
     * Setter for <code>user_resource_type.update_at</code>.
     */
    public void setUpdateAt(LocalDateTime value);

    /**
     * Getter for <code>user_resource_type.update_at</code>.
     */
    public LocalDateTime getUpdateAt();

    /**
     * Setter for <code>user_resource_type.version</code>.
     */
    public void setVersion(Integer value);

    /**
     * Getter for <code>user_resource_type.version</code>.
     */
    public Integer getVersion();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IUserResourceType
     */
    public void from(IUserResourceType from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IUserResourceType
     */
    public <E extends IUserResourceType> E into(E into);
}
