/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.user.repository.generate.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IUserRole extends Serializable {

    /**
     * Setter for <code>user_role.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>user_role.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>user_role.code</code>.
     */
    public void setCode(String value);

    /**
     * Getter for <code>user_role.code</code>.
     */
    public String getCode();

    /**
     * Setter for <code>user_role.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>user_role.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>user_role.desc</code>.
     */
    public void setDesc(String value);

    /**
     * Getter for <code>user_role.desc</code>.
     */
    public String getDesc();

    /**
     * Setter for <code>user_role.enabled</code>.
     */
    public void setEnabled(Boolean value);

    /**
     * Getter for <code>user_role.enabled</code>.
     */
    public Boolean getEnabled();

    /**
     * Setter for <code>user_role.create_by</code>.
     */
    public void setCreateBy(String value);

    /**
     * Getter for <code>user_role.create_by</code>.
     */
    public String getCreateBy();

    /**
     * Setter for <code>user_role.create_at</code>.
     */
    public void setCreateAt(LocalDateTime value);

    /**
     * Getter for <code>user_role.create_at</code>.
     */
    public LocalDateTime getCreateAt();

    /**
     * Setter for <code>user_role.update_by</code>.
     */
    public void setUpdateBy(String value);

    /**
     * Getter for <code>user_role.update_by</code>.
     */
    public String getUpdateBy();

    /**
     * Setter for <code>user_role.update_at</code>.
     */
    public void setUpdateAt(LocalDateTime value);

    /**
     * Getter for <code>user_role.update_at</code>.
     */
    public LocalDateTime getUpdateAt();

    /**
     * Setter for <code>user_role.version</code>.
     */
    public void setVersion(Integer value);

    /**
     * Getter for <code>user_role.version</code>.
     */
    public Integer getVersion();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IUserRole
     */
    public void from(IUserRole from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IUserRole
     */
    public <E extends IUserRole> E into(E into);
}
