/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.user.repository.generate.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IUserAccount extends Serializable {

    /**
     * Setter for <code>user_account.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>user_account.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>user_account.code</code>.
     */
    public void setCode(String value);

    /**
     * Getter for <code>user_account.code</code>.
     */
    public String getCode();

    /**
     * Setter for <code>user_account.source</code>.
     */
    public void setSource(Short value);

    /**
     * Getter for <code>user_account.source</code>.
     */
    public Short getSource();

    /**
     * Setter for <code>user_account.means</code>.
     */
    public void setMeans(Short value);

    /**
     * Getter for <code>user_account.means</code>.
     */
    public Short getMeans();

    /**
     * Setter for <code>user_account.email</code>.
     */
    public void setEmail(String value);

    /**
     * Getter for <code>user_account.email</code>.
     */
    public String getEmail();

    /**
     * Setter for <code>user_account.mobile</code>.
     */
    public void setMobile(String value);

    /**
     * Getter for <code>user_account.mobile</code>.
     */
    public String getMobile();

    /**
     * Setter for <code>user_account.password</code>.
     */
    public void setPassword(String value);

    /**
     * Getter for <code>user_account.password</code>.
     */
    public String getPassword();

    /**
     * Setter for <code>user_account.external_id</code>.
     */
    public void setExternalId(String value);

    /**
     * Getter for <code>user_account.external_id</code>.
     */
    public String getExternalId();

    /**
     * Setter for <code>user_account.creat_ip</code>.
     */
    public void setCreatIp(String value);

    /**
     * Getter for <code>user_account.creat_ip</code>.
     */
    public String getCreatIp();

    /**
     * Setter for <code>user_account.last_login_ip</code>.
     */
    public void setLastLoginIp(String value);

    /**
     * Getter for <code>user_account.last_login_ip</code>.
     */
    public String getLastLoginIp();

    /**
     * Setter for <code>user_account.login_times</code>.
     */
    public void setLoginTimes(Integer value);

    /**
     * Getter for <code>user_account.login_times</code>.
     */
    public Integer getLoginTimes();

    /**
     * Setter for <code>user_account.status</code>.
     */
    public void setStatus(Short value);

    /**
     * Getter for <code>user_account.status</code>.
     */
    public Short getStatus();

    /**
     * Setter for <code>user_account.create_by</code>.
     */
    public void setCreateBy(String value);

    /**
     * Getter for <code>user_account.create_by</code>.
     */
    public String getCreateBy();

    /**
     * Setter for <code>user_account.create_at</code>.
     */
    public void setCreateAt(LocalDateTime value);

    /**
     * Getter for <code>user_account.create_at</code>.
     */
    public LocalDateTime getCreateAt();

    /**
     * Setter for <code>user_account.update_by</code>.
     */
    public void setUpdateBy(String value);

    /**
     * Getter for <code>user_account.update_by</code>.
     */
    public String getUpdateBy();

    /**
     * Setter for <code>user_account.update_at</code>.
     */
    public void setUpdateAt(LocalDateTime value);

    /**
     * Getter for <code>user_account.update_at</code>.
     */
    public LocalDateTime getUpdateAt();

    /**
     * Setter for <code>user_account.version</code>.
     */
    public void setVersion(Integer value);

    /**
     * Getter for <code>user_account.version</code>.
     */
    public Integer getVersion();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IUserAccount
     */
    public void from(IUserAccount from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IUserAccount
     */
    public <E extends IUserAccount> E into(E into);
}
