/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.user.repository.generate.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IUserProfile extends Serializable {

    /**
     * Setter for <code>user_profile.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>user_profile.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>user_profile.code</code>.
     */
    public void setCode(String value);

    /**
     * Getter for <code>user_profile.code</code>.
     */
    public String getCode();

    /**
     * Setter for <code>user_profile.first_name</code>.
     */
    public void setFirstName(String value);

    /**
     * Getter for <code>user_profile.first_name</code>.
     */
    public String getFirstName();

    /**
     * Setter for <code>user_profile.last_name</code>.
     */
    public void setLastName(String value);

    /**
     * Getter for <code>user_profile.last_name</code>.
     */
    public String getLastName();

    /**
     * Setter for <code>user_profile.nick_name</code>.
     */
    public void setNickName(String value);

    /**
     * Getter for <code>user_profile.nick_name</code>.
     */
    public String getNickName();

    /**
     * Setter for <code>user_profile.avatar</code>.
     */
    public void setAvatar(String value);

    /**
     * Getter for <code>user_profile.avatar</code>.
     */
    public String getAvatar();

    /**
     * Setter for <code>user_profile.gender</code>.
     */
    public void setGender(Short value);

    /**
     * Getter for <code>user_profile.gender</code>.
     */
    public Short getGender();

    /**
     * Setter for <code>user_profile.create_by</code>.
     */
    public void setCreateBy(String value);

    /**
     * Getter for <code>user_profile.create_by</code>.
     */
    public String getCreateBy();

    /**
     * Setter for <code>user_profile.create_at</code>.
     */
    public void setCreateAt(LocalDateTime value);

    /**
     * Getter for <code>user_profile.create_at</code>.
     */
    public LocalDateTime getCreateAt();

    /**
     * Setter for <code>user_profile.update_by</code>.
     */
    public void setUpdateBy(String value);

    /**
     * Getter for <code>user_profile.update_by</code>.
     */
    public String getUpdateBy();

    /**
     * Setter for <code>user_profile.update_at</code>.
     */
    public void setUpdateAt(LocalDateTime value);

    /**
     * Getter for <code>user_profile.update_at</code>.
     */
    public LocalDateTime getUpdateAt();

    /**
     * Setter for <code>user_profile.version</code>.
     */
    public void setVersion(Integer value);

    /**
     * Getter for <code>user_profile.version</code>.
     */
    public Integer getVersion();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IUserProfile
     */
    public void from(IUserProfile from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IUserProfile
     */
    public <E extends IUserProfile> E into(E into);
}
