/*
 * This file is generated by jOOQ.
 */
package oceanstars.ecommerce.user.repository.generate.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IUserPermissionOperation extends Serializable {

    /**
     * Setter for <code>user_permission_operation.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>user_permission_operation.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>user_permission_operation.code</code>.
     */
    public void setCode(String value);

    /**
     * Getter for <code>user_permission_operation.code</code>.
     */
    public String getCode();

    /**
     * Setter for <code>user_permission_operation.behavior</code>.
     */
    public void setBehavior(String value);

    /**
     * Getter for <code>user_permission_operation.behavior</code>.
     */
    public String getBehavior();

    /**
     * Setter for <code>user_permission_operation.desc</code>.
     */
    public void setDesc(String value);

    /**
     * Getter for <code>user_permission_operation.desc</code>.
     */
    public String getDesc();

    /**
     * Setter for <code>user_permission_operation.enabled</code>.
     */
    public void setEnabled(Boolean value);

    /**
     * Getter for <code>user_permission_operation.enabled</code>.
     */
    public Boolean getEnabled();

    /**
     * Setter for <code>user_permission_operation.create_by</code>.
     */
    public void setCreateBy(String value);

    /**
     * Getter for <code>user_permission_operation.create_by</code>.
     */
    public String getCreateBy();

    /**
     * Setter for <code>user_permission_operation.create_at</code>.
     */
    public void setCreateAt(LocalDateTime value);

    /**
     * Getter for <code>user_permission_operation.create_at</code>.
     */
    public LocalDateTime getCreateAt();

    /**
     * Setter for <code>user_permission_operation.update_by</code>.
     */
    public void setUpdateBy(String value);

    /**
     * Getter for <code>user_permission_operation.update_by</code>.
     */
    public String getUpdateBy();

    /**
     * Setter for <code>user_permission_operation.update_at</code>.
     */
    public void setUpdateAt(LocalDateTime value);

    /**
     * Getter for <code>user_permission_operation.update_at</code>.
     */
    public LocalDateTime getUpdateAt();

    /**
     * Setter for <code>user_permission_operation.version</code>.
     */
    public void setVersion(Integer value);

    /**
     * Getter for <code>user_permission_operation.version</code>.
     */
    public Integer getVersion();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IUserPermissionOperation
     */
    public void from(IUserPermissionOperation from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IUserPermissionOperation
     */
    public <E extends IUserPermissionOperation> E into(E into);
}
