oceanstars:
  data:
    redis:
      default:
        host: ${REDIS_DEFAULT_SERVICE_HOST}
        password: ${REDIS_DEFAULT_AUTH}
        port: 6379
        database: 2
      session:
        host: ${REDIS_SESSION_SERVICE_HOST}
        password: ${REDIS_SESSION_AUTH}
        port: 6379
        database: 1