redis:
  configuration: default,session
default:
  redis:
    host: ${REDIS_DEFAULT_SERVICE_HOST}
    port: 6379
    database: 0
    password: ${REDIS_DEFAULT_AUTH}
    maxTotal: 20 #连接池最大连接数（负值表示没有限制）
    maxWaitMillis: 3000 #连接池最大阻塞等待时间（负值表示没有限制）
    maxIdle: 20 #连接池最大空闭连接数
    timeout: 3000 #连接超时时间（毫秒）
session:
  redis:
    host: ${REDIS_SESSION_SERVICE_HOST}
    port: 6379
    database: 0
    password: ${REDIS_SESSION_AUTH}
    maxTotal: 20 #连接池最大连接数（负值表示没有限制）
    maxWaitMillis: 3000 #连接池最大阻塞等待时间（负值表示没有限制）
    maxIdle: 20 #连接池最大空闭连接数
    timeout: 3000 #连接超时时间（毫秒）